// RentSketch Embed Loader v3 — validated, responsive, tenant catalog + designer.
(function () {
  'use strict';
  var RENTSKETCH_ORIGIN='https://rentsketch.com', API_ORIGIN='https://rentsketch-api-production.up.railway.app', VERSION='3';
  var script=document.currentScript||document.scripts[document.scripts.length-1];
  function attr(name,fallback){var v=script.getAttribute(name);return v==null||v===''?fallback:v;}
  var tenant=attr('data-tenant',null),embedKey=attr('data-embed-key',''),targetId=attr('data-target','rentsketch-embed'),fixedHeight=attr('data-height',null),mode=attr('data-mode','inline'),orderId=attr('data-order-id',''),customerToken=attr('data-customer-token',''),showCatalog=attr('data-show-catalog','true')!=='false',modalOverlay=null;
  function target(){return document.getElementById(targetId);}
  function emit(el,name,detail){el.dispatchEvent(new CustomEvent(name,{detail:detail||{}}));}
  function money(v){if(v===null||v===undefined||v==='')return'Ask for pricing';var n=Number(v);return Number.isFinite(n)?('$'+n.toFixed(2)+'/day'):'Ask for pricing';}
  function label(v){return String(v||'Other').replace(/_/g,' ').replace(/\b\w/g,function(c){return c.toUpperCase();});}
  function messageBox(el,title,body){el.innerHTML='';var box=document.createElement('div');box.style.cssText='font-family:system-ui,-apple-system,Segoe UI,sans-serif;padding:24px;border:1px solid #dfe6ed;border-radius:14px;background:#fff;color:#172536;box-shadow:0 10px 35px rgba(25,45,70,.08)';var h=document.createElement('strong');h.textContent=title;h.style.display='block';h.style.marginBottom='6px';var p=document.createElement('span');p.textContent=body;p.style.color='#667589';p.style.fontSize='14px';box.appendChild(h);box.appendChild(p);el.appendChild(box);}
  function buildSrc(){var p=['tenant='+encodeURIComponent(tenant),'embed=1','v='+VERSION,'parentOrigin='+encodeURIComponent(window.location.origin)];if(embedKey)p.push('embedKey='+encodeURIComponent(embedKey));if(orderId)p.push('orderId='+encodeURIComponent(orderId));if(customerToken)p.push('customerToken='+encodeURIComponent(customerToken));return RENTSKETCH_ORIGIN+'/designer/?'+p.join('&');}
  function makeIframe(){var f=document.createElement('iframe');f.src=buildSrc();f.title='RentSketch Event Designer';f.setAttribute('allow','clipboard-write; fullscreen');f.setAttribute('loading','eager');f.style.cssText='width:100%;border:0;display:block;background:#fff;height:'+(fixedHeight?Number(fixedHeight):860)+'px';return f;}
  function closeModal(){if(modalOverlay&&modalOverlay.parentNode)modalOverlay.parentNode.removeChild(modalOverlay);modalOverlay=null;}
  function bindMessages(iframe){var lastHeight=Number(fixedHeight)||860,lastResizeAt=0;window.addEventListener('message',function(event){if(event.origin!==RENTSKETCH_ORIGIN||event.source!==iframe.contentWindow)return;var msg=event.data||{};if(!msg||typeof msg.type!=='string')return;if(msg.type==='rentsketch.resize'&&!fixedHeight){var now=Date.now(),h=Math.max(650,Math.min(1800,Number(msg.height)||860));if(Math.abs(h-lastHeight)>=24&&now-lastResizeAt>120){lastHeight=h;lastResizeAt=now;iframe.style.height=h+'px';}}else if(msg.type==='rentsketch.ready')emit(iframe,'rentsketch:ready',msg);else if(msg.type==='rentsketch.designSaved')emit(iframe,'rentsketch:designSaved',msg);else if(msg.type==='rentsketch.quoteRequested')emit(iframe,'rentsketch:quoteRequested',msg);else if(msg.type==='rentsketch.close')closeModal();});}
  async function validate(){if(!tenant||!embedKey)throw new Error('This RentSketch installation is missing its tenant or embed key.');var r=await fetch(API_ORIGIN+'/api/embed/validate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tenant:tenant,embedKey:embedKey,parentOrigin:window.location.origin})});var d=await r.json().catch(function(){return{};});if(!r.ok||!d.ok)throw new Error(d.error||'RentSketch could not validate this website.');return d;}
  async function getProducts(){var r=await fetch(API_ORIGIN+'/api/tenants/'+encodeURIComponent(tenant)+'/products',{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('Catalog unavailable');var d=await r.json();return(d.products||[]).filter(function(p){return p.active!==false;});}
  function catalogShell(products){var wrap=document.createElement('section');wrap.className='rentsketch-catalog';wrap.style.cssText='font-family:system-ui,-apple-system,Segoe UI,sans-serif;background:#f7f9fc;border:1px solid #e2e8f0;border-radius:18px;padding:20px;margin:0 0 18px;color:#172536';var head=document.createElement('div');head.style.cssText='display:flex;gap:12px;justify-content:space-between;align-items:end;flex-wrap:wrap;margin-bottom:16px';head.innerHTML='<div><div style="font-size:12px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:#667589">Rental Catalog</div><h2 style="margin:3px 0 0;font-size:24px;line-height:1.15">Browse Available Rentals</h2><div style="font-size:13px;color:#667589;margin-top:5px">'+products.length+' items from this rental company</div></div>';
    var search=document.createElement('input');search.type='search';search.placeholder='Search rentals…';search.style.cssText='width:min(330px,100%);padding:11px 13px;border:1px solid #ccd6e2;border-radius:10px;background:#fff;font:inherit;box-sizing:border-box';head.appendChild(search);wrap.appendChild(head);
    var cats=document.createElement('div');cats.style.cssText='display:flex;gap:7px;overflow:auto;padding-bottom:10px;margin-bottom:8px';var categories=['all'].concat(Array.from(new Set(products.map(function(p){return p.category||'other';}))).sort());categories.forEach(function(c){var b=document.createElement('button');b.type='button';b.textContent=c==='all'?'All':label(c);b.dataset.cat=c;b.style.cssText='white-space:nowrap;border:1px solid #d7e0ea;background:'+(c==='all'?'#172536':'#fff')+';color:'+(c==='all'?'#fff':'#334155')+';border-radius:999px;padding:7px 11px;font:700 12px system-ui;cursor:pointer';cats.appendChild(b);});wrap.appendChild(cats);
    var grid=document.createElement('div');grid.style.cssText='display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:12px';wrap.appendChild(grid);var active='all';
    function paint(){var q=search.value.trim().toLowerCase(),shown=products.filter(function(p){return(active==='all'||(p.category||'other')===active)&&(!q||[p.name,p.category,p.sku].join(' ').toLowerCase().indexOf(q)>=0);});grid.innerHTML='';shown.forEach(function(p){var card=document.createElement('article');card.style.cssText='background:#fff;border:1px solid #e1e7ef;border-radius:13px;overflow:hidden;min-width:0;box-shadow:0 2px 8px rgba(15,23,42,.04)';var media=document.createElement('div');media.style.cssText='height:135px;background:#eef2f6;display:flex;align-items:center;justify-content:center;overflow:hidden';if(p.photo_url){var img=document.createElement('img');img.src=p.photo_url;img.alt=p.name||'';img.loading='lazy';img.style.cssText='width:100%;height:100%;object-fit:cover;display:block';img.onerror=function(){media.innerHTML='<span style="font-size:34px">📦</span>';};media.appendChild(img);}else media.innerHTML='<span style="font-size:34px">📦</span>';var body=document.createElement('div');body.style.cssText='padding:11px 12px 13px';var cat=document.createElement('div');cat.textContent=label(p.category);cat.style.cssText='font-size:10px;text-transform:uppercase;letter-spacing:.06em;color:#7b8796;font-weight:800;margin-bottom:4px';var name=document.createElement('div');name.textContent=p.name||'Rental item';name.style.cssText='font-weight:750;font-size:14px;line-height:1.25;min-height:35px';var price=document.createElement('div');price.textContent=money(p.price_per_day);price.style.cssText='font-size:14px;font-weight:800;color:#1976e9;margin-top:8px';body.appendChild(cat);body.appendChild(name);body.appendChild(price);card.appendChild(media);card.appendChild(body);grid.appendChild(card);});if(!shown.length)grid.innerHTML='<div style="grid-column:1/-1;padding:24px;text-align:center;color:#667589">No rentals match this search.</div>';}
    search.addEventListener('input',paint);cats.addEventListener('click',function(e){var b=e.target.closest('button[data-cat]');if(!b)return;active=b.dataset.cat;Array.prototype.forEach.call(cats.children,function(x){var on=x.dataset.cat===active;x.style.background=on?'#172536':'#fff';x.style.color=on?'#fff':'#334155';});paint();});paint();return wrap;}
  async function renderInline(el){el.innerHTML='';if(showCatalog){try{var products=await getProducts();if(products.length)el.appendChild(catalogShell(products));}catch(e){console.warn('[RentSketch catalog]',e.message);}}var iframe=makeIframe();el.appendChild(iframe);bindMessages(iframe);}
  function renderButton(el){el.innerHTML='';var btn=document.createElement('button');btn.type='button';btn.textContent=el.getAttribute('data-label')||'Visualize My Event';btn.style.cssText='background:#1976e9;color:#fff;border:0;padding:13px 20px;border-radius:10px;font:700 15px system-ui;cursor:pointer;box-shadow:0 8px 22px rgba(25,118,233,.22)';btn.addEventListener('click',function(){closeModal();modalOverlay=document.createElement('div');modalOverlay.style.cssText='position:fixed;inset:0;background:rgba(13,25,39,.58);z-index:999999;display:flex;align-items:center;justify-content:center;padding:16px;backdrop-filter:blur(5px)';var panel=document.createElement('div');panel.style.cssText='background:#fff;width:min(1280px,100%);height:min(92vh,1000px);border-radius:18px;overflow:hidden;position:relative;box-shadow:0 30px 90px rgba(0,0,0,.25)';var close=document.createElement('button');close.type='button';close.textContent='×';close.setAttribute('aria-label','Close');close.style.cssText='position:absolute;right:12px;top:10px;z-index:3;width:38px;height:38px;border-radius:50%;border:1px solid #d9e1e8;background:#fff;font-size:24px;cursor:pointer';close.addEventListener('click',closeModal);var iframe=makeIframe();iframe.style.height='100%';panel.appendChild(close);panel.appendChild(iframe);modalOverlay.appendChild(panel);document.body.appendChild(modalOverlay);bindMessages(iframe);});el.appendChild(btn);}
  async function init(){var el=target();if(!el){console.error('[RentSketch] Missing #'+targetId);return;}messageBox(el,'Loading your event designer…','Connecting this website to RentSketch.');try{var handshake=await validate();if(mode==='button')renderButton(el);else await renderInline(el);emit(el,'rentsketch:validated',handshake);}catch(err){messageBox(el,'RentSketch needs attention',err.message||'This integration could not be loaded.');console.error('[RentSketch embed]',err);}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.RentSketchEmbed={version:VERSION,close:closeModal};
})();