// Real designer controls and scene store; renderer boundary is isolated from WebGL.
const {JSDOM}=require('jsdom'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),dom=new JSDOM(fs.readFileSync(path.join(root,'designer/index.html'),'utf8'),{url:'https://rentsketch.com/designer/?tenant=generic',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,d=w.document,context=dom.getInternalVMContext(),cache=new Map();
w.RentSketchEventPass={canEdit:()=>true,hasPaidEvent:()=>false};w.ResizeObserver=class{observe(){}disconnect(){}};w.ACTIVE_TENANT={slug:'generic',name:'RentSketch'};w.RENTSKETCH_API_URL='https://api.test';w.alert=()=>{};
let rendered=null,callbacks=null,captures=0;
const renderer={rebuild:s=>{rendered=s;},update:s=>{rendered=s;},setScene:()=>{},matchPhoto:()=>true,orbit360:()=>true,fitCamera:()=>{},inside:()=>{},captureImage:()=>{assert.ok(d.body.classList.contains('photo-preview-mode'),'export captures the visible preview, not the calibration overlay');assert.ok(!rendered.photoLayoutModel);captures++;return 'data:image/png;base64,AA==';}};
const canvas=d.getElementById('canvas');for(const [key,value] of [['offsetWidth',1000],['offsetHeight',600],['offsetParent',d.body]])Object.defineProperty(canvas,key,{get:()=>value});
function moduleFor(file){
 file=file.split('?')[0];if(cache.has(file))return cache.get(file);
 let m;if(file.endsWith('/js/ui/view3d.js'))m=new vm.SyntheticModule(['init'],function(){this.setExport('init',(host,cbs)=>{callbacks=cbs;return renderer;});},{context,identifier:file});
 else m=new vm.SourceTextModule(fs.readFileSync(file,'utf8'),{context,identifier:file,initializeImportMeta(meta){meta.url=require('node:url').pathToFileURL(file).href;},importModuleDynamically:async(spec,ref)=>{const dep=await load(path.resolve(path.dirname(ref.identifier),spec));if(dep.status!=='evaluated')await dep.evaluate();return dep;}});
 cache.set(file,m);return m;
}
async function load(file){const m=moduleFor(file);if(m.status==='unlinked')await m.link((spec,ref)=>moduleFor(path.resolve(path.dirname(ref.identifier),spec)));return m;}
const tick=()=>new Promise(r=>setTimeout(r,60));const click=selector=>{const el=d.querySelector(selector);assert.ok(el,selector);el.click();};
(async()=>{
 await(await load(path.join(root,'script.js'))).evaluate();const b=w.FriendlyBridge;
 const photo={id:'photo-mode-fixture',url:'https://api.test/api/consumer/background-photo/photo-mode-fixture?t=fixture',mimeType:'image/jpeg',widthPx:1600,heightPx:1000};
 const table={id:'table1',kind:'table',tableId:'banquet-6ft',shape:'rect',widthFt:6,depthFt:2.5,x:3,y:4,seatCount:6,chairId:'plastic-white',photoPlacement:{x:28,y:35,rotationDeg:0}};
 b.loadScene({tentId:'pole-20x20',objects:[table,{id:'dance1',kind:'dance',widthFt:3,depthFt:3,x:1,y:1,photoPlacement:{x:20,y:25,rotationDeg:0}},{id:'dance2',kind:'dance',widthFt:3,depthFt:3,x:4,y:1,photoPlacement:{x:23,y:25,rotationDeg:0}}],backgroundPhoto:photo,surfaceType:'grass',viewMode:'photo'});await tick();
 assert.equal(b.getScene().sceneOptions.guests,false,'new ordinary designs do not create a crowd');
 assert.equal(d.querySelector('#viewModePhoto').getAttribute('aria-selected'),'true');assert.ok(d.body.classList.contains('photo-preview-mode'));assert.equal(rendered.backgroundPhoto.id,photo.id);assert.ok(!rendered.photoLayoutModel);
 click('#viewMode3d');await tick();assert.equal(d.querySelector('#viewMode3d').getAttribute('aria-selected'),'true');assert.equal(rendered.photoLayoutModel,true);assert.equal(rendered.objects[0].photoPlacement.x,28,'3D keeps the same event placement');assert.equal(b.getScene().backgroundPhoto.id,photo.id,'switching mode never strips saved photo data');
 click('#viewModePhoto');await tick();click('#view3dAdjustPhoto');await tick();assert.ok(d.body.classList.contains('photo-edit-mode'));assert.equal(b.getScene().viewMode,'photo','calibration is a local editor state, not an invalid persisted mode');assert.ok(!d.querySelector('[data-photo-calibration-panel]').hidden);
 click('[data-photo-confirm-scale]');assert.match(d.querySelector('#photoScaleStatus').textContent,/align corners/,'accepting default reference numbers does not claim aligned scale');
 await b.goToReview();assert.equal(captures,1);assert.match(d.querySelector('.review-layout-visual figcaption').textContent,/camera and scale are estimates/);assert.equal(b.getScene().viewMode,'photo');
 click('#btnBackToDesigner');click('#view3dAdjustPhoto');await tick();let printCalls=0;w.print=()=>{printCalls++;assert.ok(d.querySelector('#step-review').classList.contains('active'));assert.match(d.querySelector('.review-layout-visual figcaption').textContent,/camera and scale are estimates/);};w.eval(fs.readFileSync(path.join(root,'js/ui/review-actions.js'),'utf8'));click('#btnQuickPrint');for(let wait=0;wait<20&&!printCalls;wait++)await tick();assert.equal(printCalls,1,'Quick Print awaits prepared photo review');click('#btnBackToDesigner');click('#viewMode3d');await tick();callbacks.onPhotoMove('__photo_tent__',{x:10,y:12,rotationDeg:15});callbacks.onPhotoMove('table1',{x:30,y:32,rotationDeg:0});click('#btnUndo');assert.equal(b.getScene().objects[0].photoPlacement.x,28);assert.equal(b.getScene().photoTentPlacement.x,10,'rental undo retains preceding tent move');click('#btnUndo');assert.equal(b.getScene().photoTentPlacement,null,'main tent drag is undoable');click('#btnRedo');assert.equal(b.getScene().photoTentPlacement.rotationDeg,15);click('#btnUndo');callbacks.onPhotoMove('dance1',{x:24,y:27,rotationDeg:0});let floor=b.getScene().objects.filter(o=>o.kind==='dance');assert.deepEqual(Array.from(floor,o=>[o.photoPlacement.x,o.photoPlacement.y]),[[24,27],[27,27]],'dance floor moves as one group in photo-world coordinates');
 b.state.selectedId='table1';b.refreshAll();click('[data-role="insp-rotate"]');let item=b.getScene().objects.find(o=>o.id==='table1');assert.equal(item.photoPlacement.rotationDeg,90);assert.equal(item.photoPlacement.x,28);assert.equal(item.photoPlacement.y,35);assert.equal(item.widthFt,6);assert.equal(item.depthFt,2.5);const space=(await load(path.join(root,'js/core/world-space.js'))).namespace;const geometry=(await load(path.join(root,'js/core/photo-geometry.js'))).namespace;const polygon=space.objectGroundFootprint(geometry.rentalPhotoPlacement(item,rendered.tent,rendered.photoSite,rendered.photoTentPlacement));const xs=polygon.map(p=>p.x),ys=polygon.map(p=>p.y);assert.equal(Math.max(...xs)-Math.min(...xs),2.5,'rotating6ft table changes its physical X extent to2.5ft');assert.equal(Math.max(...ys)-Math.min(...ys),6);
 click('[data-role="insp-duplicate"]');const copy=b.getScene().objects.at(-1);assert.notEqual(copy.id,item.id);assert.equal(copy.photoPlacement.x,item.photoPlacement.x+2);assert.equal(copy.photoPlacement.y,item.photoPlacement.y+2);click('#btnUndo');assert.equal(b.getScene().objects.length,3,'duplicate undo is atomic');click('#btnUndo');const unrotated=b.getScene().objects.find(o=>o.id==='table1');assert.equal(unrotated.photoPlacement.rotationDeg,0);assert.equal(unrotated.photoPlacement.x,28,'rotate undo restores original world position');
 const saved=JSON.parse(JSON.stringify(b.getScene()));saved.sceneOptions.guests=true;b.loadScene(saved);assert.equal(b.getScene().sceneOptions.guests,true,'explicit saved guest preference is preserved');
 const frame=role=>({...photo,id:'scan-'+role,url:photo.url+'&view='+role,role});b.loadScene({...saved,venueScan:{frames:['left','center','right'].map(frame),baselineFt:6},viewMode:'3d'});await tick();
 for(const [status,label] of [['failed','Scale check failed'],['insufficient','Unverified model distance'],['valid','only A→B independently checked']]){
  callbacks.onScanReconstruction({ready:true,validation:{status},measurementPolicy:{estimated:true},metrics:{viewCount:3}});callbacks.onMeasurement({formatted:'12 ft · estimate'});
  assert.ok(d.querySelector('#view3dMeasure').title.includes(label),status+' confidence is present beside the measurement');assert.equal(rendered.scanValidation.status,status);assert.equal(rendered.scanMeasurementPolicy.estimated,true);
  const hint=d.querySelector('#canvasHint').textContent;assert.ok(hint.includes(status==='failed'?'scale check failed':status==='valid'?'only A→B independently checked':'scale unverified'),hint);
 }
 callbacks.onScanReconstruction({ready:false,loading:true});assert.equal(rendered.scanValidation,null,'stale check cannot survive a new reconstruction');
 console.log('PASS photo mode controls: correct selected mode, shared world placement, measured-vs-aligned scale, photo editor review capture, grouped dance move, rotate/duplicate, and opt-in guests. No network writes.');w.close();
})().catch(e=>{console.error(e);w.close();process.exitCode=1;});
