// RentSketch anonymous autosave/resume. Product tent previews are intentionally excluded.
(function(){
'use strict';
var params=new URLSearchParams(location.search),started=false;
function start(skipRestore){if(started)return;started=true;
var api=window.RENTSKETCH_API_URL,slug=window.RENTSKETCH_TENANT_SLUG||'generic';if(!api||!slug){started=false;setTimeout(function(){start(skipRestore);},100);return;}
var KEY='rentsketch-autosave:'+slug,SESSION='rentsketch-anon-session',timer=null,saving=false,lastJson='',lastId=null,retryAfter=0,pending=false;
function sessionId(){try{var id=localStorage.getItem(SESSION);if(!id){id=(crypto.randomUUID?crypto.randomUUID():'rs-'+Date.now()+'-'+Math.random().toString(36).slice(2));localStorage.setItem(SESSION,id);}return id;}catch(e){return null;}}
function bridge(){return window.FriendlyBridge||{};}function scene(){var b=bridge();return b.getScene?b.getScene():null;}function meta(){var b=bridge(),s=b.state||{};return{eventType:s.eventType||null,guestCount:s.guestCount||null};}
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'null');}catch(e){return null;}}function write(v){try{localStorage.setItem(KEY,JSON.stringify(v));}catch(e){}}
function snapshotLocal(sc,id){write({id:id||lastId||null,scene:sc,savedAt:new Date().toISOString(),tenant:slug});}
function payload(sc,m,sid){return JSON.stringify({scene:sc,eventType:m.eventType,guestCount:m.guestCount,anonymousSessionId:sid,schemaVersion:1});}
async function sendSave(sc,m,sid,id){var base=api+'/api/tenants/'+encodeURIComponent(slug)+'/designs',isUpdate=!!(id&&sid),r=await fetch(isUpdate?base+'/'+encodeURIComponent(id):base,{method:isUpdate?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:payload(sc,m,sid)});if(isUpdate&&r.status===404){lastId=null;r=await fetch(base,{method:'POST',headers:{'Content-Type':'application/json'},body:payload(sc,m,sid)});}return r;}
function waitForActiveSave(){return new Promise(function(resolve,reject){var started=Date.now(),timer=setInterval(function(){if(!saving){clearInterval(timer);resolve(lastId);return;}if(Date.now()-started>10000){clearInterval(timer);reject(new Error('Timed out waiting for the current design save.'));}},50);});}
async function save(strict){if(saving){pending=true;var existing=await waitForActiveSave();if(strict){var current=scene(),currentJson='';try{currentJson=current?JSON.stringify(current):'';}catch(e){}if(currentJson&&currentJson!==lastJson)return save(true);}return existing;}var sc=scene();if(!sc||!Array.isArray(sc.objects)){if(strict)throw new Error('The current design is not available to save.');return lastId;}var json;try{json=JSON.stringify(sc);}catch(e){if(strict)throw e;return lastId;}if(json===lastJson&&lastId)return lastId;snapshotLocal(sc,lastId);if(Date.now()<retryAfter){if(strict)throw new Error('Design saving is temporarily rate limited. Please wait a moment and try again.');return lastId;}saving=true;try{var m=meta(),sid=sessionId(),r=await sendSave(sc,m,sid,lastId);if(r.status===429){retryAfter=Date.now()+60000;throw new Error('Design saving is temporarily rate limited. Please wait a moment and try again.');}var d={};try{d=await r.json();}catch(e){}if(!r.ok)throw new Error(d.error||('autosave '+r.status));lastId=d.id||lastId;lastJson=json;snapshotLocal(sc,lastId);window.dispatchEvent(new CustomEvent('rentsketch:autosaved',{detail:{id:lastId,updated:!!d.updated}}));return lastId;}catch(e){console.warn('[RentSketch] autosave failed; local recovery retained',e);if(strict)throw e;return lastId;}finally{saving=false;if(pending){pending=false;schedule();}}}
function schedule(){clearTimeout(timer);timer=setTimeout(function(){save(false);},1500);}
function restorePrompt(){var saved=read(),b=bridge();if(!saved||saved.tenant!==slug||!saved.scene||!b.loadScene)return;var age=Date.now()-Date.parse(saved.savedAt||0);if(!Number.isFinite(age)||age>30*24*60*60*1000)return;var hasObjects=Array.isArray(saved.scene.objects)&&saved.scene.objects.length>0;if(!hasObjects)return;setTimeout(function(){if(window.RENTSKETCH_TENT_PREVIEW)return;if(confirm('Continue your saved RentSketch design?\n\nChoose Cancel to start a fresh design.')){if(b.loadScene(saved.scene)){lastJson=JSON.stringify(saved.scene);lastId=saved.id||null;window.dispatchEvent(new CustomEvent('rentsketch:draftResumed'));}}else{try{localStorage.removeItem(KEY);}catch(e){}}},350);}
function restoreWhenAllowed(){var entry=document.querySelector('.rs-entry');if(!entry){restorePrompt();return;}var done=false;function resume(){if(done)return;done=true;window.removeEventListener('rentsketch:entryAccepted',resume);restorePrompt();}window.addEventListener('rentsketch:entryAccepted',resume,{once:true});}
function emergencyLocalSave(){var sc=scene();if(!sc||!Array.isArray(sc.objects))return;snapshotLocal(sc,lastId);}
window.RentSketchAutosave={flush:function(){return save(true);},getDesignId:function(){return lastId;}};
function bind(){var b=bridge();if(!b.getScene){setTimeout(bind,100);return;}if(!skipRestore)restoreWhenAllowed();document.addEventListener('pointerup',schedule,true);document.addEventListener('change',schedule,true);document.addEventListener('keyup',function(e){if(e.key==='Delete'||e.key==='Backspace')schedule();},true);window.addEventListener('pagehide',emergencyLocalSave);document.addEventListener('visibilitychange',function(){if(document.visibilityState==='hidden')emergencyLocalSave();});window.addEventListener('rentsketch:requestSave',schedule);}
bind();
}
window.addEventListener('rentsketch:designStarted',function(){start(true);},{once:true});
function boot(){if(params.get('focus')==='tent'&&params.get('autoplace')==='1')return;start(false);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
