// RentSketch realistic installation crew planner.
// Timing is deliberately human-paced: walk to a part, work it, then move to the next part.
export const SETUP_TIMING={walkSeconds:1.35,workSeconds:2.4,heavyWorkSeconds:3.4,stagePauseSeconds:.7};
export function crewSize(widthFt){return Math.max(2,Math.min(6,Math.ceil(Number(widthFt||20)/10)));}
export function perimeterWorkPoints(tent){const w=Number(tent?.widthFt||20),l=Number(tent?.lengthFt||20),hw=w/2,hl=l/2,out=[];for(let x=-hw;x<=hw+.01;x+=10){out.push({x:Math.min(x,hw),z:-hl,job:'stake'});out.push({x:Math.min(x,hw),z:hl,job:'stake'});}for(let z=-hl+10;z<hl;z+=10){out.push({x:-hw,z,job:'stake'});out.push({x:hw,z,job:'stake'});}return out;}
export function buildWorkPlan(tent){const edge=perimeterWorkPoints(tent),center=(tent?.centerPoles||[]).map(p=>({x:(p.x??tent.widthFt/2)-tent.widthFt/2,z:(p.y??tent.lengthFt/2)-tent.lengthFt/2,job:'center-pole'}));return [...edge,...center,{x:0,z:0,job:'roof'},{x:0,z:0,job:'finish'}];}
export function assignCrew(tent){const count=crewSize(tent?.widthFt),pts=buildWorkPlan(tent),roles=['lead','stake','pole','canvas','finish','support'];return Array.from({length:count},(_,i)=>({id:i,role:roles[i]||'support',route:pts.filter((_,n)=>n%count===i)}));}
export function workerPose(worker,routeProgress,timeSec){const route=worker.route||[];if(!route.length)return{x:0,z:0,y:0,heading:0,walk:0,work:0,job:'idle'};const p=Math.max(0,Math.min(.9999,routeProgress))*route.length,i=Math.floor(p),f=p-i,a=route[i],b=route[Math.min(i+1,route.length-1)],dx=b.x-a.x,dz=b.z-a.z,working=f>.68;return{x:a.x+dx*Math.min(1,f/.68),z:a.z+dz*Math.min(1,f/.68),y:0,heading:Math.atan2(dx,dz),walk:working?0:Math.sin(timeSec*6+i)*.32,work:working?Math.sin(timeSec*5.5)*.42:0,job:working?b.job:a.job};}
export function stageForJob(job){return job==='stake'?'ground':job==='center-pole'||job==='pole'?'frame':job==='roof'?'roof':job==='finish'?'valance':'frame';}
export function stageDurationMs(stage,itemCount){const n=Math.max(1,itemCount||1),per=stage==='roof'?900:stage==='frame'?780:stage==='ground'?650:stage==='tables'?520:460;return Math.max(1800,Math.min(12000,1100+n*per));}
