// RentSketch tenant-customer entry experience
(function () {
  'use strict';
  var APP_VERSION = 'Beta 0.9';
  var LEGAL_VERSION = '2026-09-17';
  var q = new URLSearchParams(location.search);
  var embedded = q.get('embed') === '1';
  if (!embedded) return;
  var tenantSlug = q.get('tenant') || 'generic';
  var isTentPreview = q.get('view') === '3d' && q.get('focus') === 'tent' && q.get('autoplace') === '1';
  var tenant = window.ACTIVE_TENANT || {};
  var tenantName = tenant.name || (tenantSlug === 'friendly' ? 'Friendly Party Rental' : 'your rental company');
  var supportEmail = tenant.contactEmail || '';
  var storageKey = 'rentsketch:entry-accepted:' + tenantSlug + ':' + LEGAL_VERSION;
  var layoutKey = 'rentsketch:layout:' + tenantSlug;

  var css=document.createElement('style');css.textContent='.rs-beta{position:fixed;right:12px;bottom:12px;z-index:9000;background:#172536;color:#fff;border-radius:999px;padding:7px 11px;font:700 11px system-ui;box-shadow:0 3px 12px #0002}.rs-entry{position:fixed;inset:0;z-index:2147483000;background:rgba(10,22,35,.72);display:flex;align-items:center;justify-content:center;padding:18px;font-family:system-ui,-apple-system,Segoe UI,sans-serif;color:#172536;backdrop-filter:blur(8px)}.rs-card{width:min(620px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:24px;padding:28px;box-shadow:0 30px 90px #0005}.rs-eyebrow{font-size:12px;font-weight:850;letter-spacing:.09em;text-transform:uppercase;color:#2f7a3c}.rs-card h1{font-size:30px;line-height:1.05;margin:8px 0 10px}.rs-card p{line-height:1.55;color:#526171}.rs-features{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:18px 0}.rs-feature{background:#f4f7f5;border-radius:12px;padding:11px;font-size:13px;font-weight:650}.rs-note{background:#fff8e8;border:1px solid #f2dfac;border-radius:13px;padding:12px 14px;font-size:13px}.rs-actions{display:flex;gap:10px;margin-top:18px;flex-wrap:wrap}.rs-btn{border:0;border-radius:11px;padding:12px 17px;font:750 14px system-ui;cursor:pointer}.rs-primary{background:#2f7a3c;color:#fff}.rs-secondary{background:#edf2f5;color:#172536}.rs-legal{font-size:11px!important;margin:13px 0 0!important}.rs-link{border:0;background:none;padding:0;color:#1766b1;text-decoration:underline;cursor:pointer;font:inherit}.rs-modal{position:fixed;inset:0;z-index:2147483600;background:#0009;display:flex;align-items:center;justify-content:center;padding:18px;font-family:system-ui}.rs-modal-card{width:min(720px,100%);max-height:88vh;overflow:auto;background:#fff;border-radius:20px;padding:25px;color:#172536}.rs-modal-card h2{margin-top:0}.rs-modal-card h3{margin-bottom:5px}.rs-modal-card p,.rs-modal-card li{line-height:1.5;color:#526171;font-size:14px}.rs-help{position:fixed;right:12px;bottom:52px;z-index:9001}.rs-help button{border:1px solid #d8e0e7;background:#fff;border-radius:999px;padding:8px 12px;font:700 12px system-ui;box-shadow:0 3px 12px #0002}.rs-recovery{position:fixed;inset:0;z-index:2147483500;background:#f5f8f6;display:none;align-items:center;justify-content:center;padding:20px;font-family:system-ui}.rs-recovery .rs-card{text-align:center}.rs-help-menu button{display:block;width:100%;text-align:left;margin:5px 0;padding:10px;border:0;border-radius:9px;background:#f3f6f8;cursor:pointer}@media(max-width:560px){.rs-entry{padding:10px}.rs-card{padding:20px;border-radius:18px}.rs-card h1{font-size:25px}.rs-features{grid-template-columns:1fr}.rs-actions .rs-btn{width:100%}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;animation:none!important;transition:none!important}}';document.head.appendChild(css);
  function modal(title,html){var wrap=document.createElement('div');wrap.className='rs-modal';wrap.setAttribute('role','dialog');wrap.setAttribute('aria-modal','true');wrap.innerHTML='<div class="rs-modal-card"><h2>'+title+'</h2>'+html+'<div class="rs-actions"><button class="rs-btn rs-primary" data-close>Close</button></div></div>';document.body.appendChild(wrap);var close=wrap.querySelector('[data-close]');close.focus();close.onclick=function(){wrap.remove();};wrap.addEventListener('click',function(e){if(e.target===wrap)wrap.remove();});wrap.addEventListener('keydown',function(e){if(e.key==='Escape')wrap.remove();});}
  function terms(){modal('RentSketch Terms of Use','<p><strong>Effective '+LEGAL_VERSION+' · Early Access</strong></p><h3>Planning tool</h3><p>RentSketch creates visual planning concepts. Layouts are not engineering drawings, certified site plans, fire-code determinations, permit approvals, utility markings, or safety certifications. Final dimensions, placement, capacity, anchoring, clearances and installation requirements must be verified by the rental provider and other appropriate professionals.</p><h3>Your rental provider</h3><p>'+tenantName+' is responsible for its inventory, pricing, availability, delivery, installation and rental agreement. A RentSketch layout does not reserve equipment or guarantee availability or pricing.</p><h3>Early Access</h3><p>RentSketch is actively being improved. Features may change and may occasionally be unavailable. Do not rely on the software as the sole source for safety-critical decisions.</p><h3>Acceptable use & intellectual property</h3><p>Use RentSketch lawfully and do not attempt to disrupt, reverse engineer, or misuse the service. Feedback you voluntarily provide may be used to improve the product.</p>');}
  function privacy(){modal('RentSketch Privacy Policy','<p><strong>Effective '+LEGAL_VERSION+'</strong></p><p>RentSketch uses information needed to provide the designer. This embedded experience may store your entry acknowledgment and draft layout in your browser using local storage. If you enter contact/event information, save a design, request a quote, or send feedback, that information may be sent to RentSketch and/or '+tenantName+' to provide the feature requested.</p><h3>Technical information</h3><p>Normal web-service logs can include browser/device details, IP address, requested pages, timestamps and errors for security and troubleshooting.</p><h3>Rental-company sharing</h3><p>Information submitted for a rental quote or design handoff may be shared with the rental company whose website launched RentSketch. Their own privacy practices may also apply.</p><h3>Your choices</h3><p>You can clear locally saved RentSketch information through your browser.</p>');}
  function howTo(){modal('How to use RentSketch','<ol><li>Choose or confirm your tent.</li><li>Add tables, chairs and supported event items.</li><li>Drag items to arrange your layout.</li><li>Switch between 2D and 3D to review the setup.</li><li>Save or send the layout when available.</li></ol>');}
  function whatsNew(){modal("What's New",'<p><strong>'+APP_VERSION+'</strong></p><p>Tenant website integration, tent-specific previews, 3D framing, customer welcome and recovery, plus tenant-scoped draft resume.</p>');}
  function feedback(kind){if(supportEmail){location.href='mailto:'+encodeURIComponent(supportEmail)+'?subject='+encodeURIComponent('RentSketch '+kind+' — '+tenantName)+'&body='+encodeURIComponent('Tell us what happened or what you would like added.\n\nRentSketch: '+APP_VERSION+'\nTenant: '+tenantSlug+'\nView: '+(isTentPreview?'Tent preview':'Designer'));}else{modal(kind,'<p>Feedback submission is not configured for this rental company yet. Please use the rental company’s normal contact method.</p>');}}
  function safeGet(key){try{return localStorage.getItem(key);}catch(e){return null;}} function safeSet(key,val){try{localStorage.setItem(key,val);return true;}catch(e){return false;}}
  function getSavedDraft(){if(isTentPreview)return null;var raw=safeGet(layoutKey);if(!raw)return null;try{var saved=JSON.parse(raw);return saved&&saved.scene&&Array.isArray(saved.scene.objects)&&saved.scene.objects.length?saved:null;}catch(e){return null;}}
  function resumeDraft(){var saved=getSavedDraft(),b=window.FriendlyBridge;if(!saved||!b||!b.loadScene)return false;var ok=b.loadScene(saved.scene);if(ok)window.dispatchEvent(new CustomEvent('rentsketch:draftResumed'));return ok;}
  function installAutosave(){if(isTentPreview)return;var tries=0;function attach(){tries++;var b=window.FriendlyBridge;if(!b||!b.getScene){if(tries<100)setTimeout(attach,100);return;}var last='';setInterval(function(){if(!document.body.classList.contains('designer-active'))return;try{var scene=b.getScene();if(!scene||!Array.isArray(scene.objects)||!scene.objects.length)return;var serialized=JSON.stringify(scene);if(serialized===last)return;last=serialized;safeSet(layoutKey,JSON.stringify({version:1,tenant:tenantSlug,savedAt:new Date().toISOString(),scene:scene}));}catch(e){}},1500);}attach();} installAutosave();
  var badge=document.createElement('div');badge.className='rs-beta';badge.textContent='RentSketch · '+APP_VERSION;document.body.appendChild(badge);var help=document.createElement('div');help.className='rs-help';help.innerHTML='<button type="button" aria-label="RentSketch help">Help & Feedback</button>';document.body.appendChild(help);
  help.firstChild.onclick=function(){modal('Help & Feedback','<div class="rs-help-menu"><button data-a="how">How to Use RentSketch</button><button data-a="problem">Report a Problem</button><button data-a="idea">Suggest an Idea</button><button data-a="new">What’s New</button><button data-a="terms">Terms of Use</button><button data-a="privacy">Privacy Policy</button></div>');setTimeout(function(){var m=document.querySelector('.rs-modal:last-of-type');if(!m)return;m.addEventListener('click',function(e){var a=e.target.dataset.a;if(!a)return;m.remove();if(a==='how')howTo();if(a==='problem')feedback('Problem Report');if(a==='idea')feedback('Feature Idea');if(a==='new')whatsNew();if(a==='terms')terms();if(a==='privacy')privacy();});},0);};
  var recovery=document.createElement('div');recovery.className='rs-recovery';recovery.innerHTML='<div class="rs-card"><div class="rs-eyebrow">RentSketch Early Access</div><h2>We couldn’t load the 3D preview</h2><p>You can retry the preview or continue in 2D.</p><div class="rs-actions" style="justify-content:center"><button class="rs-btn rs-primary" data-retry>Try Again</button><button class="rs-btn rs-secondary" data-2d>Open in 2D</button><a class="rs-btn rs-secondary" data-fullscreen href="#" target="_blank" rel="noopener">Open Full Screen</a></div></div>';document.body.appendChild(recovery);recovery.querySelector('[data-retry]').onclick=function(){location.reload();};recovery.querySelector('[data-2d]').onclick=function(){q.set('view','2d');q.delete('autoplace');location.search=q.toString();};recovery.querySelector('[data-fullscreen]').href=location.href;window.RentSketchCustomerEntry={showRecovery:function(){recovery.style.display='flex';},terms:terms,privacy:privacy};
  if(safeGet(storageKey)==='accepted'){if(!isTentPreview){setTimeout(function(){var saved=getSavedDraft();if(saved)modal('Continue your event design?','<p>We found a draft saved on this device for '+tenantName+'.</p><div class="rs-actions"><button class="rs-btn rs-primary" data-resume>Continue My Design</button><button class="rs-btn rs-secondary" data-new>Start Fresh</button></div>');setTimeout(function(){var m=document.querySelector('.rs-modal:last-of-type');if(!m)return;var r=m.querySelector('[data-resume]'),n=m.querySelector('[data-new]');if(r)r.onclick=function(){if(resumeDraft())m.remove();};if(n)n.onclick=function(){try{localStorage.removeItem(layoutKey);}catch(e){}m.remove();};},0);},400);}return;}
  var entry=document.createElement('div');entry.className='rs-entry';entry.setAttribute('role','dialog');entry.setAttribute('aria-modal','true');entry.setAttribute('aria-labelledby','rsWelcomeTitle');entry.innerHTML='<div class="rs-card"><div class="rs-eyebrow">Early Access · '+tenantName+'</div><h1 id="rsWelcomeTitle">See your event before the big day.</h1><p>Welcome to RentSketch, the interactive event-design experience used by '+tenantName+'. Build and explore your setup before you book.</p><div class="rs-features"><div class="rs-feature">Choose your tent</div><div class="rs-feature">Add tables & chairs</div><div class="rs-feature">Arrange your layout</div><div class="rs-feature">Explore in 2D & 3D</div></div><div class="rs-note"><strong>RentSketch is currently in Early Access.</strong><br>We’re actively building and improving it. Features may change or occasionally be unavailable. We welcome feedback.</div><div class="rs-actions"><button class="rs-btn rs-primary" data-start>Start Designing →</button><button class="rs-btn rs-secondary" data-feedback>Send Feedback</button></div><p class="rs-legal">By continuing, you agree to the <button class="rs-link" data-terms>Terms of Use</button> and acknowledge the <button class="rs-link" data-privacy>Privacy Policy</button>. Layouts are visual planning aids and do not reserve or guarantee rental availability or pricing.</p><p class="rs-legal">Event design powered by RentSketch · '+APP_VERSION+'</p></div>';document.body.appendChild(entry);entry.querySelector('[data-start]').focus();entry.querySelector('[data-start]').onclick=function(){safeSet(storageKey,'accepted');entry.remove();window.dispatchEvent(new CustomEvent('rentsketch:entryAccepted'));};entry.querySelector('[data-feedback]').onclick=function(){feedback('Feedback');};entry.querySelector('[data-terms]').onclick=terms;entry.querySelector('[data-privacy]').onclick=privacy;
})();
