import { TABLETOP, tabletopType } from '../data/tabletop.js';
import { escapeHtml as esc } from './equipment-controls.js';
const CATEGORIES=[['all','All rentals'],['tent','Tents & sidewalls'],['table','Tables'],['chair','Chairs'],['linen','Linens'],['tabletop','Tabletop & serving'],['inflatable','Bounce houses & slides'],['effects','Foam & effects'],['lighting','Lighting'],['climate','Fans'],['flooring','Dance floors & stages'],['service','Food & beverage service'],['concessions','Concessions'],['games','Games'],['audio','Audio & podiums'],['power','Power'],['photo','Photo booths'],['accessories','Accessories']];
export function equipmentPhoto(p){return p?.photoUrl?`<img class="inventory-photo" src="${esc(p.photoUrl)}" alt="${esc(p.name)}" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span class="inventory-placeholder" hidden>Product photo unavailable</span>`:`<span class="inventory-placeholder"><svg viewBox="0 0 64 48" aria-hidden="true"><path d="M12 15 32 5 52 15 52 35 32 45 12 35Z M12 15 32 25 52 15 M32 25V45" fill="none" stroke="currentColor" stroke-width="2"/></svg><small>Illustrative model</small></span>`;}
export function equipmentInspector(item,p){p=p||{name:item.name||'Equipment',widthFt:item.widthFt,depthFt:item.depthFt};return `<button class="btn-tertiary inspector-close" data-role="inspector-close">Close</button><h3>${esc(p.name)}</h3>${equipmentPhoto(p)}<p>${item.widthFt} × ${item.depthFt} ft footprint</p><p class="equipment-note">${p.dimensionsConfirmed?'Catalog dimensions supplied. Confirm required operating clearance.':'Approximate model dimensions. Staff must confirm the actual item and operating clearance.'}</p><p>${p.pricePerDay==null?'Price needs confirmation':'$'+Number(p.pricePerDay).toFixed(2)+'/day'}</p><div class="inspector-actions">${['rotate','duplicate','delete'].map(a=>`<button type="button" class="btn-secondary" data-role="insp-${a}" data-id="${esc(item.id)}">${a[0].toUpperCase()+a.slice(1)}</button>`).join('')}</div>`;}
export function inventoryBrowser(catalog,objects=[],{query='',category='all'}={}){
 const rows=[]; const add=(items,cat,role)=>{for(const p of items||[])rows.push({p,cat,role:cat==='chair'&&p.isThrone?'accent-chair':role});};
 add(catalog.tents,'tent','tent-card');add(catalog.tables,'table','table-card');add(catalog.chairs,'chair','chair-card');add(catalog.inflatables,'inflatable','inflatable-card');
 for(const p of TABLETOP)rows.push({p,cat:'tabletop',role:'inventory-open',drawer:'tables'});
 const accessories=catalog.accessories||[], equipment=catalog.equipment||[];
 const upgrades=new Map();
 for(const p of equipment){const a=accessories.find(a=>a.productId&&a.productId===p.productId);if(p.type==='generic'&&a&&a.accessoryType!=='generic')upgrades.set(p.id,a);}
 for(const p of equipment){const a=upgrades.get(p.id);rows.push({p:a||p,cat:p.category||'accessories',role:a?'accessory-card':'equipment-card'});}
 // Compatibility for integrations that provide a pre-resolved accessory catalog.
 if(!(catalog.products||[]).length)for(const p of accessories)if(!equipment.some(e=>e.productId&&e.productId===p.productId))rows.push({p,cat:'accessories',role:'accessory-card'});
 for(const [cat,name,drawer] of [['linen','Linens & table styling','tables'],['lighting','Lighting for your tent','lighting'],['flooring','Dance floor sizes','dance'],['tent','Solid & window sidewalls','tent']])rows.push({cat,p:{id:drawer,name},role:'inventory-open',drawer});
 const mapped=new Set([...(catalog.tents||[]),...(catalog.tables||[]),...(catalog.chairs||[]),...(catalog.inflatables||[]),...(catalog.equipment||[])].map(p=>p.productId));
 const unresolved=(catalog.products||[]).filter(p=>p.active!==false&&!mapped.has(p.id)&&!tabletopType(p)&&!(p.external_id&&p.external_id===p.visual_model_id)&&!['linen','lighting','dance_floor','package'].includes(p.category)&&!/sidewall|side wall/i.test(p.name||''));
 const tokens=query.toLowerCase().trim().split(/\s+/).filter(Boolean);
 const filtered=rows.filter(r=>(category==='all'||r.cat===category)&&tokens.every(q=>(r.p.name+' '+r.cat).toLowerCase().includes(q)));
 return `<div class="inventory-browser"><div class="inventory-heading"><span>BUILD YOUR EVENT</span><h3>Everything in one place.</h3><p>Pick a rental, place it, then fine-tune its details.</p></div><label class="inventory-search"><span class="sr-only">Search rentals</span><input type="search" data-role="inventory-query" value="${esc(query)}" placeholder="Search tents, foam, coolers…" autocomplete="off"></label><div class="inventory-categories" aria-label="Rental categories">${CATEGORIES.filter(([id])=>id==='all'||rows.some(r=>r.cat===id)).map(([id,label])=>`<button type="button" data-role="inventory-category" data-category="${id}" aria-pressed="${id===category}">${label}</button>`).join('')}</div><p class="inventory-results" role="status">${filtered.length} options${query?' matching “'+esc(query)+'”':''}</p><div class="inventory-grid">${filtered.map(({p,cat,role,drawer})=>{const count=objects.filter(o=>[o.equipmentId,o.accessoryId,o.tableId,o.inflatableId,o.chairId].includes(p.id)||(p.productId&&o.productId===p.productId)).length;return `<button type="button" class="inventory-card" data-role="${role}" data-id="${esc(p.id)}"${drawer?' data-drawer="'+drawer+'"':''}>${equipmentPhoto(p)}<span class="inventory-card-copy"><small>${esc(CATEGORIES.find(c=>c[0]===cat)?.[1]||cat)}</small><strong>${esc(p.name)}</strong><span>${p.widthFt?(p.widthFt+' × '+(p.depthFt||p.lengthFt)+' ft'):'Choose options'}${p.dimensionsConfirmed===false?' · approx.':''}</span><span class="inventory-price">${drawer?(cat==='tabletop'?'Choose a table →':'Customize →'):p.pricePerDay==null?'Confirm pricing':'$'+Number(p.pricePerDay).toFixed(2)+'/day'}</span>${count?'<span class="inventory-count">'+count+' in layout</span>':''}${p.isPreview?'<span class="inventory-preview">Planning model · availability unconfirmed</span>':''}</span></button>`;}).join('')}</div>${!filtered.length?'<div class="inventory-empty">No matches. Try a shorter name or another category.</div>':''}${category==='all'&&!query&&unresolved.length?`<details class="inventory-unmapped"><summary>${unresolved.length} catalog items need configuration</summary><p>These products are in the rental catalog but do not yet have a placement model. They have not been added to your layout.</p><ul>${unresolved.map(p=>'<li>'+esc(p.name)+'</li>').join('')}</ul></details>`:''}<p class="inventory-footnote">Product selection is not a reservation. Approximate models are labeled; your rental team confirms measurements, setup and availability.</p></div>`;
}
