// RentSketch Direct Consumer Event Pass paywall.
// Wraps window.FriendlyBridge.useRecommendedLayout / customizeFromScratch so
// a direct consumer (no tenant, or the generic RentSketch catalog) must
// unlock a $9.99 / 30-day Event Pass before entering the editor. Tenant
// customers (e.g. Friendly Party Rental) are NOT gated here - their access
// rules are separate and will be built later, per docs/ROADMAP.md. The
// server is authoritative for the entitlement check; this file never trusts
// the Stripe success URL by itself.

(function () {
  var ANON_SESSION_KEY = 'rentsketch_anon_session';
    var DESIGN_ID_KEY = 'rentsketch_design_id';

      function getAnonymousSessionId() {
          var id = window.localStorage.getItem(ANON_SESSION_KEY);
              if (!id) {
                    id = 'anon_' + Date.now().toString(36) + '_' + Math.random().toString(36).slice(2);
                          window.localStorage.setItem(ANON_SESSION_KEY, id);
                              }
                                  return id;
                                    }

                                      function apiUrl(path) {
                                          return (window.RENTSKETCH_API_URL || '') + path;
                                            }

                                              function createAnonymousDesign() {
                                                  return fetch(apiUrl('/api/consumer/designs'), {
                                                        method: 'POST',
                                                              headers: { 'Content-Type': 'application/json' },
                                                                    body: JSON.stringify({
                                                                            scene: { note: 'RentSketch direct consumer design' },
                                                                                    anonymousSessionId: getAnonymousSessionId(),
                                                                                            schemaVersion: 1,
                                                                                                  }),
                                                                                                      })
                                                                                                            .then(function (r) { return r.json(); })
                                                                                                                  .then(function (created) {
                                                                                                                          window.localStorage.setItem(DESIGN_ID_KEY, created.id);
                                                                                                                                  return created.id;
                                                                                                                                        });
                                                                                                                                          }
                                                                                                                                          
                                                                                                                                            function checkEntitlement(designId) {
                                                                                                                                                return fetch(apiUrl('/api/consumer/designs/' + designId + '/entitlement'))
                                                                                                                                                      .then(function (r) { return r.ok ? r.json() : { active: false }; })
                                                                                                                                                            .catch(function () { return { active: false }; });
                                                                                                                                                              }
                                                                                                                                                              
                                                                                                                                                                function startCheckout(designId, email) {
                                                                                                                                                                    return fetch(apiUrl('/api/consumer/designs/' + designId + '/event-pass/checkout-session'), {
                                                                                                                                                                          method: 'POST',
                                                                                                                                                                                headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                      body: JSON.stringify({ customerEmail: email, origin: window.location.origin }),
                                                                                                                                                                                          })
                                                                                                                                                                                                .then(function (r) {
                                                                                                                                                                                                        return r.json().then(function (body) { return { ok: r.ok, body: body }; });
                                                                                                                                                                                                              })
                                                                                                                                                                                                                    .then(function (result) {
                                                                                                                                                                                                                            if (!result.ok || !result.body.url) {
                                                                                                                                                                                                                                      throw new Error(result.body.error || 'Could not start checkout');
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                      window.location.href = result.body.url;
                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                function injectStyles() {
                                                                                                                                                                                                                                                                    var style = document.createElement('style');
                                                                                                                                                                                                                                                                        style.textContent =
                                                                                                                                                                                                                                                                              '.paywall-overlay{position:fixed;inset:0;background:rgba(0,0,0,0.55);display:flex;align-items:center;justify-content:center;z-index:9999;}' +
                                                                                                                                                                                                                                                                                    '.paywall-modal{background:#fff;border-radius:12px;padding:32px;max-width:380px;width:90%;text-align:center;font-family:inherit;}' +
                                                                                                                                                                                                                                                                                          '.paywall-modal h2{margin:0 0 8px;}' +
                                                                                                                                                                                                                                                                                                '.paywall-price{font-size:32px;font-weight:700;margin:12px 0;}' +
                                                                                                                                                                                                                                                                                                      '.paywall-label{display:block;text-align:left;font-size:13px;margin-top:12px;margin-bottom:4px;color:#555;}' +
                                                                                                                                                                                                                                                                                                            '.paywall-email{width:100%;padding:10px;border:1px solid #ccc;border-radius:6px;box-sizing:border-box;font-size:14px;}' +
                                                                                                                                                                                                                                                                                                                  '.paywall-error{color:#c0392b;font-size:13px;min-height:18px;margin-top:6px;text-align:left;}' +
                                                                                                                                                                                                                                                                                                                        '.paywall-modal .btn-primary{width:100%;margin-top:14px;padding:12px;border-radius:8px;border:none;background:#5b3df0;color:#fff;font-size:15px;cursor:pointer;}' +
                                                                                                                                                                                                                                                                                                                              '.paywall-modal .btn-link{display:block;width:100%;margin-top:10px;background:none;border:none;color:#777;text-decoration:underline;cursor:pointer;font-size:13px;}' +
                                                                                                                                                                                                                                                                                                                                    '.paywall-unlocked-banner{position:fixed;top:16px;left:50%;transform:translateX(-50%);background:#1e8e3e;color:#fff;padding:10px 20px;border-radius:8px;z-index:9999;font-size:14px;}';
                                                                                                                                                                                                                                                                                                                                        document.head.appendChild(style);
                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                            function showPaywallModal(onUnlock) {
                                                                                                                                                                                                                                                                                                                                                var overlay = document.createElement('div');
                                                                                                                                                                                                                                                                                                                                                    overlay.className = 'paywall-overlay';
                                                                                                                                                                                                                                                                                                                                                        overlay.innerHTML =
                                                                                                                                                                                                                                                                                                                                                              '<div class="paywall-modal">' +
                                                                                                                                                                                                                                                                                                                                                                      '<h2>Unlock Your Event</h2>' +
                                                                                                                                                                                                                                                                                                                                                                              '<p>Save, edit and explore your complete event design for 30 days.</p>' +
                                                                                                                                                                                                                                                                                                                                                                                      '<div class="paywall-price">$9.99</div>' +
                                                                                                                                                                                                                                                                                                                                                                                              '<label class="paywall-label">Email (for your receipt, and to find your design later)</label>' +
                                                                                                                                                                                                                                                                                                                                                                                                      '<input type="email" class="paywall-email" placeholder="you@example.com" />' +
                                                                                                                                                                                                                                                                                                                                                                                                              '<div class="paywall-error"></div>' +
                                                                                                                                                                                                                                                                                                                                                                                                                      '<button type="button" class="btn-primary paywall-submit">Unlock My Event</button>' +
                                                                                                                                                                                                                                                                                                                                                                                                                              '<button type="button" class="btn-link paywall-cancel">Not yet</button>' +
                                                                                                                                                                                                                                                                                                                                                                                                                                    '</div>';
                                                                                                                                                                                                                                                                                                                                                                                                                                        document.body.appendChild(overlay);
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                            var emailInput = overlay.querySelector('.paywall-email');
                                                                                                                                                                                                                                                                                                                                                                                                                                                var errorBox = overlay.querySelector('.paywall-error');
                                                                                                                                                                                                                                                                                                                                                                                                                                                    var submitBtn = overlay.querySelector('.paywall-submit');
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                        overlay.querySelector('.paywall-cancel').addEventListener('click', function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                              overlay.remove();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      submitBtn.addEventListener('click', function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            var email = emailInput.value.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!email || email.indexOf('@') === -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          errorBox.textContent = 'Please enter a valid email address.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              errorBox.textContent = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    submitBtn.disabled = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          submitBtn.textContent = 'Redirecting to secure checkout...';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                createAnonymousDesign()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .then(function (designId) { return startCheckout(designId, email); })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .catch(function (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          errorBox.textContent = err.message || 'Something went wrong. Please try again.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    submitBtn.disabled = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              submitBtn.textContent = 'Unlock My Event';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              function isGenericConsumer() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  var tenant = window.ACTIVE_TENANT;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return !tenant || tenant.slug === 'generic';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          function gate(originalFn) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!isGenericConsumer()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return originalFn.apply(this, arguments);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        var existingDesignId = window.localStorage.getItem(DESIGN_ID_KEY);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              var args = arguments;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    var self = this;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          var proceed = function () { originalFn.apply(self, args); };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (existingDesignId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        checkEntitlement(existingDesignId).then(function (entitlement) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (entitlement.active) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              proceed();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    showPaywallModal(proceed);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    showPaywallModal(proceed);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  function installPaywallGate() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      var Bridge = window.FriendlyBridge;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!Bridge || Bridge.__paywallInstalled) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Bridge.__paywallInstalled = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  var originalUse = Bridge.useRecommendedLayout;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      var originalCustomize = Bridge.customizeFromScratch;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (typeof originalUse === 'function') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Bridge.useRecommendedLayout = gate(originalUse);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (typeof originalCustomize === 'function') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Bridge.customizeFromScratch = gate(originalCustomize);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      function checkReturnFromCheckout() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          var params = new URLSearchParams(window.location.search);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              var designId = params.get('design');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  var payment = params.get('payment');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!designId || payment !== 'success') return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          checkEntitlement(designId).then(function (entitlement) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!entitlement.active) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      window.localStorage.setItem(DESIGN_ID_KEY, designId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            var banner = document.createElement('div');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  banner.className = 'paywall-unlocked-banner';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        banner.textContent = 'Your Event Pass is active - enjoy 30 days of full editing access.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              document.body.appendChild(banner);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setTimeout(function () { banner.remove(); }, 6000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (window.FriendlyBridge && typeof window.FriendlyBridge.enterDesigner === 'function') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  window.FriendlyBridge.enterDesigner();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function tryInstall(attempts) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (window.FriendlyBridge) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          installPaywallGate();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                injectStyles();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      checkReturnFromCheckout();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (attempts > 200) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setTimeout(function () { tryInstall(attempts + 1); }, 50);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            tryInstall(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })();
