// RentSketch customer review actions.
(function(){
'use strict';
var quoteSubmitting=false;
function $(id){return document.getElementById(id);}function tenant(){return window.ACTIVE_TENANT||{};}function bridge(){return window.FriendlyBridge||{};}
function details(){return{name:($('customerName')||{}).value||'',email:($('customerEmail')||{}).value||'',date:($('customerDate')||{}).value||''};}function scene(){var b=bridge();return b.getScene?b.getScene():null;}
function summaryText(){var b=bridge(),s=scene(),t=tenant(),d=details();if(!s)return'RentSketch event layout';var tent=(b.TENTS||[]).find(function(x){return x.id===s.tentId;}),tables=(s.objects||[]).filter(function(x){return x.kind==='table';}),seats=tables.reduce(function(n,x){return n+(Number(x.seatCount)||0);},0);return['RentSketch Event Plan',t.name||'',d.name?('Customer: '+d.name):'',d.email?('Email: '+d.email):'',d.date?('Event date: '+d.date):'',s.guestCount?('Guests: '+s.guestCount):'',tent?('Tent: '+tent.name):'',tables.length?('Tables: '+tables.length):'',seats?('Planned seats: '+seats):'','Visual planning draft — final pricing, availability, placement, anchoring and installation must be confirmed by the rental company.'].filter(Boolean).join('\n');}
function download(){var payload={version:1,createdAt:new Date().toISOString(),tenant:{slug:window.RENTSKETCH_TENANT_SLUG||'',name:tenant().name||''},customer:details(),scene:scene()};var blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='rentsketch-event-plan.json';document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(a.href);a.remove();},1000);}
async function share(){var text=summaryText();try{if(navigator.share){await navigator.share({title:'RentSketch Event Plan',text:text});return;}await navigator.clipboard.writeText(text);alert('Event plan summary copied to your clipboard.');}catch(e){if(e&&e.name==='AbortError')return;prompt('Copy your event plan:',text);}}
function sessionId(){var k='rentsketch-anon-session';try{var id=localStorage.getItem(k);if(!id){id=(crypto.randomUUID?crypto.randomUUID():'rs-'+Date.now()+'-'+Math.random().toString(36).slice(2));localStorage.setItem(k,id);}return id;}catch(e){return null;}}
async function jsonFetch(url,options){var r=await fetch(url,options),data={};try{data=await r.json();}catch(e){}if(!r.ok)throw new Error(data.error||('Request failed ('+r.status+')'));return data;}
function notifyParent(type,detail){if(!window.parent||window.parent===window)return false;try{window.parent.postMessage(Object.assign({type:type},detail||{}),'*');return true;}catch(e){return false;}}
async function saveDesign(api,slug,s,st){var autosave=window.RentSketchAutosave;if(autosave&&typeof autosave.flush==='function'){var id=await autosave.flush();if(id)return{id:id};}return jsonFetch(api+'/api/tenants/'+encodeURIComponent(slug)+'/designs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scene:s,eventType:st.eventType||null,guestCount:st.guestCount||null,anonymousSessionId:sessionId(),schemaVersion:1})});}
async function quote(e){if(e)e.preventDefault();var btn=$('btnEmailQuote');if(quoteSubmitting||(btn&&btn.getAttribute('data-sent')==='true'))return;var d=details(),t=tenant(),b=bridge(),s=scene(),st=b.state||{},slug=t.slug||window.RENTSKETCH_TENANT_SLUG||'',api=window.RENTSKETCH_API_URL;if(!d.name||!d.email||!d.date){alert('Please enter your name, email, and event date before requesting a quote.');return;}if(!api||!slug||!s){alert('RentSketch cannot submit this request right now. Your design is still available here; please try again.');return;}var old=btn&&btn.textContent;quoteSubmitting=true;if(btn){btn.setAttribute('aria-disabled','true');btn.style.pointerEvents='none';btn.textContent='Sending…';}var success=false;try{var saved=await saveDesign(api,slug,s,st);var q=await jsonFetch(api+'/api/tenants/'+encodeURIComponent(slug)+'/quote-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({designId:saved.id,customerName:d.name,customerEmail:d.email,eventDate:d.date,guestCount:st.guestCount||null,eventType:st.eventType||null,notes:summaryText()})});success=true;var embeddedNotified=notifyParent('rentsketch.quoteRequested',{tenant:slug,quoteRequestId:q.id,designId:saved.id});if(!embeddedNotified)alert('Your quote request was received by '+(t.name||'the rental company')+'. Request '+q.id+'.');if(btn){btn.textContent='Quote Request Sent';btn.setAttribute('data-sent','true');}}catch(err){alert(err.message||'We could not submit your quote request. Your design has not been lost; please try again.');if(btn)btn.textContent=old||'Request a Quote';}finally{quoteSubmitting=false;if(btn&&!success){btn.removeAttribute('aria-disabled');btn.style.pointerEvents='';}}}
function bind(){var p=$('btnPrint'),d=$('btnDownload'),s=$('btnShare'),q=$('btnEmailQuote');if(p)p.addEventListener('click',function(){window.print();});if(d)d.addEventListener('click',download);if(s)s.addEventListener('click',share);if(q)q.addEventListener('click',quote);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
