// RentSketch customer review actions: make the existing review controls functional.
(function(){
'use strict';
function $(id){return document.getElementById(id);} function tenant(){return window.ACTIVE_TENANT||{};} function bridge(){return window.FriendlyBridge||{};}
function details(){return{name:($('customerName')||{}).value||'',email:($('customerEmail')||{}).value||'',date:($('customerDate')||{}).value||''};}
function scene(){var b=bridge();return b.getScene?b.getScene():null;} function money(n){return typeof n==='number'?'$'+n.toFixed(2):'Ask for pricing';}
function summaryText(){var b=bridge(),s=scene(),t=tenant(),d=details();if(!s)return'RentSketch event layout';var tent=(b.TENTS||[]).find(function(x){return x.id===s.tentId;});var tables=(s.objects||[]).filter(function(x){return x.kind==='table';});var seats=tables.reduce(function(n,x){return n+(Number(x.seatCount)||0);},0);return['RentSketch Event Plan',t.name||'',d.name?('Customer: '+d.name):'',d.email?('Email: '+d.email):'',d.date?('Event date: '+d.date):'',s.guestCount?('Guests: '+s.guestCount):'',tent?('Tent: '+tent.name):'',tables.length?('Tables: '+tables.length):'',seats?('Planned seats: '+seats):'','Visual planning draft — final pricing, availability, placement, anchoring and installation must be confirmed by the rental company.'].filter(Boolean).join('\n');}
function download(){var payload={version:1,createdAt:new Date().toISOString(),tenant:{slug:window.RENTSKETCH_TENANT_SLUG||'',name:tenant().name||''},customer:details(),scene:scene()};var blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='rentsketch-event-plan.json';document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(a.href);a.remove();},1000);}
async function share(){var text=summaryText();try{if(navigator.share){await navigator.share({title:'RentSketch Event Plan',text:text});return;}await navigator.clipboard.writeText(text);alert('Event plan summary copied to your clipboard.');}catch(e){if(e&&e.name==='AbortError')return;prompt('Copy your event plan:',text);}}
function quote(e){if(e)e.preventDefault();var d=details(),t=tenant();if(!d.name||!d.email||!d.date){alert('Please enter your name, email, and event date before requesting a quote.');return;}var subject='RentSketch quote request'+(d.date?' — '+d.date:'');var body=summaryText();if(t.contactEmail){location.href='mailto:'+t.contactEmail+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);return;}alert('This rental company has not configured a quote email yet. Your design remains saved on this device.');}
function bind(){var p=$('btnPrint'),d=$('btnDownload'),s=$('btnShare'),q=$('btnEmailQuote');if(p)p.addEventListener('click',function(){window.print();});if(d)d.addEventListener('click',download);if(s)s.addEventListener('click',share);if(q)q.addEventListener('click',quote);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();