import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

let renderer, scene, camera, controls, root, container, ro, raf, state, isNight=false;
let ambient, hemi, sun;
const EAVE=7;
const M={};
function mat(k,o){return M[k]||(M[k]=new THREE.MeshStandardMaterial(o));}
function box(w,h,d,m){const x=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);x.castShadow=x.receiveShadow=true;return x;}
function cyl(r,h,m,n=12){const x=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,n),m);x.castShadow=true;return x;}
function tube(a,b,r,m){const d=new THREE.Vector3().subVectors(b,a),q=cyl(r,d.length(),m,8);q.position.copy(a).add(b).multiplyScalar(.5);q.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());return q;}
const vinyl=()=>mat('vinyl',{color:0xfffdf7,roughness:.72,side:THREE.DoubleSide,transparent:true,opacity:.96});
const steel=()=>mat('steel',{color:0xa8afb2,roughness:.3,metalness:.7});
const dark=()=>mat('dark',{color:0x292d30,roughness:.45,metalness:.45});
const plastic=()=>mat('plastic',{color:0xf8f8f5,roughness:.5});
const wood=()=>mat('wood',{color:0xb98550,roughness:.5});
function peaks(t){const L=t.lengthFt,ps=(t.centerPoles||[]).map(p=>({x:(p.x||t.widthFt/2)-t.widthFt/2,z:(p.y||L/2)-L/2}));if(ps.length)return ps;const count=Math.max(1,Math.round(L/30));const a=[];for(let i=0;i<count;i++)a.push({x:0,z:(i-(count-1)/2)*30});return a;}
function peakH(t){return EAVE+Math.max(6,Math.min(11,t.widthFt*.38));}
function roof(t){const W=t.widthFt,L=t.lengthFt,h=peakH(t),g=new THREE.PlaneGeometry(W,L,Math.max(24,W),Math.max(30,L)),a=g.attributes.position,ps=peaks(t);for(let i=0;i<a.count;i++){const x=a.getX(i),z=a.getY(i),edge=Math.max(0,1-Math.abs(x)/(W/2));let y=EAVE;if(t.type==='pole'){let influence=0;for(const p of ps){const dx=(x-p.x)/(W*.55),dz=(z-p.z)/Math.max(12,L/(ps.length+1)),r=Math.sqrt(dx*dx+dz*dz);influence=Math.max(influence,Math.max(0,1-r));}y=EAVE+(h-EAVE)*Math.pow(influence,.72);const ridge=EAVE+(h-EAVE)*Math.pow(edge,1.25)*.42;y=Math.max(y,ridge);}else{y=EAVE+(h-EAVE)*Math.pow(edge,.9);}if(Math.abs(x)>W*.49)y=EAVE;a.setZ(i,y);}g.rotateX(-Math.PI/2);g.computeVertexNormals();return new THREE.Mesh(g,vinyl());}
function perimeter(t){const W=t.widthFt,L=t.lengthFt,hw=W/2,hl=L/2,p=[];for(let x=-hw;x<=hw+.1;x+=10)p.push([Math.min(x,hw),-hl],[Math.min(x,hw),hl]);for(let z=-hl+10;z<hl;z+=10)p.push([-hw,z],[hw,z]);return p;}
function tent(t,anchor){const g=new THREE.Group(),r=roof(t);r.castShadow=r.receiveShadow=true;g.add(r);const pp=perimeter(t),h=peakH(t);pp.forEach(([x,z])=>{const p=cyl(.075,EAVE,steel(),10);p.position.set(x,EAVE/2,z);g.add(p);});if(t.type==='pole')peaks(t).forEach(p=>{const q=cyl(.11,h,steel(),12);q.position.set(p.x,h/2,p.z);g.add(q);});if(t.type==='frame'){const hw=t.widthFt/2,hl=t.lengthFt/2;for(let z=-hl;z<=hl+.1;z+=10){const zz=Math.min(z,hl);g.add(tube(new THREE.Vector3(-hw,EAVE,zz),new THREE.Vector3(0,h,zz),.045,steel()));g.add(tube(new THREE.Vector3(0,h,zz),new THREE.Vector3(hw,EAVE,zz),.045,steel()));}}
 const clear=t.installationClearanceFt||6;pp.filter((_,i)=>i%2===0).forEach(([x,z])=>{const hw=t.widthFt/2,hl=t.lengthFt/2,dx=Math.abs(x)>hw*.8?Math.sign(x):0,dz=Math.abs(z)>hl*.8?Math.sign(z):0;if(!dx&&!dz)return;const ox=x+dx*clear,oz=z+dz*clear;if(anchor==='ballast'){const b=box(1.3,.7,1.3,mat('concrete',{color:0x929493,roughness:1}));b.position.set(ox,.35,oz);g.add(b);}else{g.add(tube(new THREE.Vector3(x,EAVE*.72,z),new THREE.Vector3(ox,.12,oz),.025,dark()));const s=cyl(.04,.9,dark(),8);s.position.set(ox,.35,oz);g.add(s);}});return g;}
function chair(){const g=new THREE.Group(),m=plastic(),seat=box(1.25,.12,1.15,m);seat.position.y=.92;g.add(seat);const back=box(1.25,1.1,.09,m);back.position.set(0,1.62,-.53);g.add(back);[-.48,.48].forEach(x=>[-.42,.42].forEach(z=>{const l=cyl(.035,1,dark(),8);l.position.set(x,.48,z);g.add(l);}));return g;}
function table(o){const g=new THREE.Group(),round=o.shape==='round'||Math.abs((o.widthFt||0)-(o.depthFt||0))<.2,w=o.widthFt||5,d=o.depthFt||5,top=2.45,lm=new THREE.MeshStandardMaterial({color:0xfaf8f1,roughness:.9});if(round){const r=w/2,s=new THREE.Mesh(new THREE.CylinderGeometry(r,r*.96,top,36,1,true),lm);s.position.y=top/2;g.add(s);const q=cyl(r,.08,lm,36);q.position.y=top;g.add(q);}else{const q=box(w,top,d,lm);q.position.y=top/2;g.add(q);}const n=o.seatCount||0,rr=Math.max(w,d)/2+1.05;for(let i=0;i<n;i++){const a=i/n*Math.PI*2,c=chair();c.position.set(Math.cos(a)*rr,0,Math.sin(a)*rr);c.rotation.y=-a-Math.PI/2;g.add(c);}return g;}
function dance(o){const g=new THREE.Group(),w=o.widthFt||18,d=o.depthFt||18,b=box(w,.12,d,dark());b.position.y=.06;g.add(b);for(let x=-w/2;x<w/2;x+=3)for(let z=-d/2;z<d/2;z+=3){const pw=Math.min(3,w-(x+w/2)),pd=Math.min(3,d-(z+d/2)),p=box(pw-.05,.06,pd-.05,wood());p.position.set(x+pw/2,.15,z+pd/2);g.add(p);}return g;}
function ground(t){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d');x.fillStyle='#789b5e';x.fillRect(0,0,128,128);for(let i=0;i<1800;i++){x.fillStyle=`rgba(40,90,35,${Math.random()*.18})`;x.fillRect(Math.random()*128,Math.random()*128,1,2);}const tx=new THREE.CanvasTexture(c);tx.wrapS=tx.wrapT=THREE.RepeatWrapping;tx.repeat.set(16,16);const p=new THREE.Mesh(new THREE.PlaneGeometry(t.widthFt+100,t.lengthFt+100),new THREE.MeshStandardMaterial({map:tx,roughness:1}));p.rotation.x=-Math.PI/2;p.receiveShadow=true;return p;}
function lights(t){if(!state.lightingId)return;const hw=t.widthFt/2,hl=t.lengthFt/2,h=peakH(t),ps=peaks(t),runs=[];if(t.type==='pole')ps.forEach(p=>runs.push([new THREE.Vector3(-hw,EAVE,-hl),new THREE.Vector3(p.x,h,p.z)],[new THREE.Vector3(hw,EAVE,-hl),new THREE.Vector3(p.x,h,p.z)],[new THREE.Vector3(-hw,EAVE,hl),new THREE.Vector3(p.x,h,p.z)],[new THREE.Vector3(hw,EAVE,hl),new THREE.Vector3(p.x,h,p.z)]));else for(let z=-hl;z<=hl;z+=10)runs.push([new THREE.Vector3(-hw,EAVE,z),new THREE.Vector3(hw,EAVE,z)]);runs.forEach(([A,B])=>{const dist=A.distanceTo(B),n=Math.max(4,Math.round(dist)),pts=[];for(let i=0;i<=n;i++){const q=i/n,p=A.clone().lerp(B,q);p.y-=Math.sin(Math.PI*q)*.35;pts.push(p);}root.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0x29231e})));for(let i=1;i<pts.length;i++){const bm=new THREE.MeshStandardMaterial({color:0xffe2a0,emissive:0xffad42,emissiveIntensity:isNight?1.8:.08}),b=new THREE.Mesh(new THREE.SphereGeometry(.07,7,7),bm);b.position.copy(pts[i]);root.add(b);if(isNight&&i%7===0){const l=new THREE.PointLight(0xffb65d,1.1,11,2);l.position.copy(b.position);root.add(l);}}});}
function clear(){while(root&&root.children.length)root.remove(root.children[0]);}
function rebuild(d){state=d;clear();const t=d.tent;if(!t)return;root.add(ground(t));root.add(tent(t,d.anchoringMethod));const hw=t.widthFt/2,hl=t.lengthFt/2;(d.objects||[]).forEach(o=>{let q=o.kind==='table'?table(o):o.kind==='dance'?dance(o):null;if(!q)return;q.position.set(o.x+o.widthFt/2-hw,0,o.y+o.depthFt/2-hl);root.add(q);});lights(t);applyLight();}
function applyLight(){if(!scene)return;scene.background=new THREE.Color(isNight?0x17243a:0xd9edf8);scene.fog.color.copy(scene.background);ambient.intensity=isNight?0.18:0.5;hemi.intensity=isNight?0.28:1.1;sun.intensity=isNight?0.08:2.1;renderer.toneMappingExposure=isNight?0.88:1.03;}
function frame(t){const s=Math.max(t.widthFt,t.lengthFt),d=s*1.12;camera.position.set(d*.75,d*.58,d*.9);controls.target.set(0,3,0);controls.minDistance=8;controls.maxDistance=s*3;controls.update();}
function resize(){if(!renderer||!container)return;const w=Math.max(320,container.clientWidth),h=Math.max(360,container.clientHeight);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);}
function loop(){raf=requestAnimationFrame(loop);controls.update();renderer.render(scene,camera);}
export function mount(el,data,cbs){unmount();container=el;container.innerHTML='';isNight=false;scene=new THREE.Scene();scene.fog=new THREE.Fog(0xd9edf8,120,420);root=new THREE.Group();scene.add(root);const w=Math.max(320,el.clientWidth),h=Math.max(360,el.clientHeight);camera=new THREE.PerspectiveCamera(40,w/h,.1,2000);renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.75));renderer.setSize(w,h);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;el.appendChild(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.maxPolarAngle=Math.PI/2-.03;ambient=new THREE.AmbientLight(0xffffff,.5);hemi=new THREE.HemisphereLight(0xd9efff,0x52683d,1.1);sun=new THREE.DirectionalLight(0xfff0d8,2.1);const s=Math.max(data.tent.widthFt,data.tent.lengthFt);sun.position.set(s*.7,s*1.1,s*.55);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=sun.shadow.camera.bottom=-s;sun.shadow.camera.right=sun.shadow.camera.top=s;sun.shadow.camera.far=s*4;scene.add(ambient,hemi,sun);frame(data.tent);rebuild(data);ro=new ResizeObserver(resize);ro.observe(el);loop();}
export function update(data){if(!scene)return;const changed=state?.tent?.id!==data?.tent?.id;rebuild(data);if(changed&&data.tent)frame(data.tent);}
export function toggleDayNight(){isNight=!isNight;rebuild(state);return isNight;}
export function unmount(){if(raf)cancelAnimationFrame(raf);raf=0;ro?.disconnect();ro=null;controls?.dispose();renderer?.dispose();if(container)container.innerHTML='';renderer=scene=camera=controls=root=container=null;}