(function(){
'use strict';
var API=window.RENTSKETCH_API_URL||'https://rentsketch-api-production.up.railway.app';
function active(){return (location.hash||'').replace(/^#\/?/,'').split('?')[0]==='products';}
function token(){return localStorage.getItem('rentsketch_dashboard_token');}
function tenant(){return localStorage.getItem('rentsketch_active_tenant');}
function css(){if(document.getElementById('productPhotoStyles'))return;var s=document.createElement('style');s.id='productPhotoStyles';s.textContent='.product-thumb{width:72px;height:54px;object-fit:cover;border-radius:9px;border:1px solid #e3e8ef;background:#f4f6f8;display:block}.product-thumb-empty{width:72px;height:54px;border-radius:9px;background:#f4f6f8;border:1px dashed #cbd5e1;display:flex;align-items:center;justify-content:center;font-size:10px;color:#7b8794;text-align:center}.catalog-photo-summary{display:flex;gap:10px;align-items:center;margin:10px 0 16px;padding:10px 12px;background:#f7f9fc;border:1px solid #e4e9f0;border-radius:10px;font-size:13px}.dash-table td.product-photo-cell{width:84px}';document.head.appendChild(s);}
async function load(){if(!active())return;var slug=tenant();if(!slug)return;var r=await fetch(API+'/api/tenants/'+encodeURIComponent(slug)+'/products',{headers:{Accept:'application/json',Authorization:'Bearer '+token()}});if(!r.ok)return;var d=await r.json(),map={};(d.products||[]).forEach(function(p){map[String(p.id)]=p;});var tries=0,t=setInterval(function(){tries++;if(!active()){clearInterval(t);return;}var table=document.querySelector('#dashMain .dash-table');if(!table){if(tries>40)clearInterval(t);return;}if(table.dataset.photosEnhanced){clearInterval(t);return;}table.dataset.photosEnhanced='1';css();var hr=table.querySelector('thead tr');if(hr){var th=document.createElement('th');th.textContent='Photo';hr.insertBefore(th,hr.firstChild);}var withPhoto=0;Array.prototype.forEach.call(table.querySelectorAll('tbody tr[data-id]'),function(tr){var p=map[tr.getAttribute('data-id')]||{},td=document.createElement('td');td.className='product-photo-cell';if(p.photo_url){withPhoto++;var img=document.createElement('img');img.className='product-thumb';img.src=p.photo_url;img.alt=p.name||'Rental item';img.loading='lazy';img.onerror=function(){this.replaceWith(Object.assign(document.createElement('div'),{className:'product-thumb-empty',textContent:'Image unavailable'}));};td.appendChild(img);}else{td.innerHTML='<div class="product-thumb-empty">No photo</div>';}tr.insertBefore(td,tr.firstChild);});var title=document.querySelector('#dashMain .dash-subtitle');if(title&&!document.getElementById('catalogPhotoSummary')){var box=document.createElement('div');box.id='catalogPhotoSummary';box.className='catalog-photo-summary';box.textContent=(d.products||[]).length+' products · '+withPhoto+' with photos · pricing and images shown from the tenant catalog';title.insertAdjacentElement('afterend',box);}clearInterval(t);},100);}
window.addEventListener('hashchange',function(){setTimeout(load,120);});document.addEventListener('DOMContentLoaded',function(){setTimeout(load,250);});var obs=new MutationObserver(function(){if(active())setTimeout(load,100);});document.addEventListener('DOMContentLoaded',function(){var root=document.getElementById('app')||document.body;obs.observe(root,{childList:true,subtree:true});});
})();
