const express=require('express');
const db=require('../db');
const {requireTenantRole}=require('../middleware/requireAuth');
const {PLATFORM_FEE_PERCENT}=require('../pricing');
const router=express.Router();
function getStripe(){if(!process.env.STRIPE_SECRET_KEY)return null;const Stripe=require('stripe');return new Stripe(process.env.STRIPE_SECRET_KEY);}
router.post('/:slug/connect/onboard',requireTenantRole('admin'),async(req,res)=>{const stripe=getStripe();if(!stripe)return res.status(503).json({error:'Payments are not configured for this server yet.'});try{let accountId=req.tenant.stripe_connect_account_id;if(!accountId){const account=await stripe.accounts.create({type:'express',email:req.tenant.contact_email||undefined,business_type:'company',metadata:{tenantId:req.tenant.id,tenantSlug:req.tenant.slug}});accountId=account.id;await db.query(`UPDATE tenants SET stripe_connect_account_id=$1,stripe_connect_status='pending',updated_at=now() WHERE id=$2`,[accountId,req.tenant.id]);}const origin=req.headers.origin||'https://rentsketch.com';const link=await stripe.accountLinks.create({account:accountId,refresh_url:`${origin}/dashboard/#/branding?connect=refresh`,return_url:`${origin}/dashboard/#/branding?connect=return`,type:'account_onboarding'});res.json({url:link.url});}catch(err){console.error('[connect] onboarding failed for tenant',req.tenant.slug,err.message);res.status(500).json({error:'Could not start Stripe onboarding.'});}});
router.get('/:slug/connect/status',requireTenantRole('viewer'),async(req,res)=>{res.json({status:req.tenant.stripe_connect_status||'not_connected',hasAccount:Boolean(req.tenant.stripe_connect_account_id),platformFeePercent:PLATFORM_FEE_PERCENT,canManage:['admin','owner','platform_admin'].includes(req.user.tenantRole)});});
module.exports=router;
