const express = require('express');
const db = require('../db');
const { requireTenantRole } = require('../middleware/requireAuth');
const router = express.Router();

router.get('/generic/products', async (req,res)=>{const t=(await db.query('SELECT id FROM tenants WHERE slug=$1',['generic'])).rows[0];if(!t)return res.status(404).json({error:'Generic tenant not found'});const p=await db.query('SELECT * FROM products WHERE tenant_id=$1 AND active=true ORDER BY category,sort_order',[t.id]);res.json({products:p.rows});});
router.get('/:slug/products', async (req,res)=>{const t=(await db.query('SELECT id FROM tenants WHERE slug=$1',[req.params.slug])).rows[0];if(!t)return res.status(404).json({error:'Tenant not found'});const p=await db.query('SELECT * FROM products WHERE tenant_id=$1 AND active=true ORDER BY category,sort_order',[t.id]);res.json({products:p.rows});});

router.post('/:slug/products', requireTenantRole('staff'), async (req,res)=>{const {category,name,sku,pricePerDay,priceType,widthFt,lengthFt,capacity,photoUrl,externalId,sortOrder,visualModelId}=req.body||{};if(!category||!name)return res.status(400).json({error:'category and name are required'});const r=await db.query(`INSERT INTO products (tenant_id,category,external_id,name,sku,price_per_day,price_type,width_ft,length_ft,capacity,photo_url,sort_order,visual_model_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[req.tenant.id,category,externalId||null,name,sku||null,pricePerDay||null,priceType||'per_day',widthFt||null,lengthFt||null,capacity||null,photoUrl||null,sortOrder||0,visualModelId||null]);res.status(201).json({product:r.rows[0]});});

router.patch('/:slug/products/:id', requireTenantRole('staff'), async (req,res)=>{const fields=req.body||{};const allowed=['category','name','sku','price_per_day','price_type','width_ft','length_ft','capacity','photo_url','external_id','sort_order','active','visual_model_id'];const map={pricePerDay:'price_per_day',priceType:'price_type',widthFt:'width_ft',lengthFt:'length_ft',photoUrl:'photo_url',externalId:'external_id',sortOrder:'sort_order',visualModelId:'visual_model_id'};const sets=[],values=[];let i=1;for(const [key,value] of Object.entries(fields)){const col=map[key]||key;if(!allowed.includes(col))continue;sets.push(`${col}=$${i++}`);values.push(value);}if(!sets.length)return res.status(400).json({error:'No valid fields to update'});sets.push('updated_at=now()');values.push(req.params.id,req.tenant.id);const r=await db.query(`UPDATE products SET ${sets.join(',')} WHERE id=$${i} AND tenant_id=$${i+1} RETURNING *`,values);if(!r.rows[0])return res.status(404).json({error:'Product not found'});res.json({product:r.rows[0]});});

router.delete('/:slug/products/:id', requireTenantRole('staff'), async (req,res)=>{const r=await db.query('UPDATE products SET active=false,updated_at=now() WHERE id=$1 AND tenant_id=$2 RETURNING id',[req.params.id,req.tenant.id]);if(!r.rows[0])return res.status(404).json({error:'Product not found'});res.json({ok:true});});
module.exports=router;
