const express = require('express');
const db = require('../db');
const { requireTenantRole } = require('../middleware/requireAuth');
const router = express.Router();

function text(value,max,required){if(value==null||value===''){if(required)throw new Error('required');return null;}if(typeof value!=='string')throw new Error('must be text');const v=value.trim();if(required&&!v)throw new Error('required');if(v.length>max)throw new Error(`must be ${max} characters or fewer`);return v||null;}
function number(value,min,max,integer){if(value==null||value==='')return null;const n=Number(value);if(!Number.isFinite(n)||n<min||n>max||(integer&&!Number.isInteger(n)))throw new Error(`must be ${integer?'a whole number':'a number'} between ${min} and ${max}`);return n;}
function category(value){const v=text(value,64,true);if(!/^[a-z0-9][a-z0-9_-]*$/i.test(v))throw new Error('must use letters, numbers, underscores, or hyphens');return v.toLowerCase();}
function webUrl(value){const v=text(value,2000,false);if(!v)return null;let u;try{u=new URL(v);}catch(_){throw new Error('must be a valid URL');}if(!['https:','http:'].includes(u.protocol))throw new Error('must use http or https');return u.toString();}
function normalized(input,key){switch(key){case'category':return category(input);case'name':return text(input,240,true);case'sku':return text(input,120,false);case'price_per_day':return number(input,0,1000000,false);case'price_type':{const v=text(input,40,false)||'per_day';if(!/^[a-z0-9_-]+$/i.test(v))throw new Error('must be a simple price type');return v;}case'width_ft':case'length_ft':return number(input,0,10000,false);case'capacity':return number(input,0,100000,true);case'photo_url':return webUrl(input);case'external_id':return text(input,240,false);case'sort_order':return number(input,-100000,100000,true);case'visual_model_id':return text(input,160,false);case'active':if(typeof input!=='boolean')throw new Error('must be true or false');return input;default:return input;}}
function validationError(res,key,err){return res.status(400).json({error:`${key} ${err.message||'is invalid'}`});}

router.get('/generic/products', async (req,res)=>{const t=(await db.query('SELECT id FROM tenants WHERE slug=$1',['generic'])).rows[0];if(!t)return res.status(404).json({error:'Generic tenant not found'});const p=await db.query('SELECT * FROM products WHERE tenant_id=$1 AND active=true ORDER BY category,sort_order',[t.id]);res.json({products:p.rows});});
router.get('/:slug/products', async (req,res)=>{const t=(await db.query('SELECT id FROM tenants WHERE slug=$1',[req.params.slug])).rows[0];if(!t)return res.status(404).json({error:'Tenant not found'});const p=await db.query('SELECT * FROM products WHERE tenant_id=$1 AND active=true ORDER BY category,sort_order',[t.id]);res.json({products:p.rows});});

router.post('/:slug/products', requireTenantRole('staff'), async (req,res)=>{const body=req.body||{},map={category:'category',name:'name',sku:'sku',pricePerDay:'price_per_day',priceType:'price_type',widthFt:'width_ft',lengthFt:'length_ft',capacity:'capacity',photoUrl:'photo_url',externalId:'external_id',sortOrder:'sort_order',visualModelId:'visual_model_id'},v={};for(const [key,col] of Object.entries(map)){try{v[col]=normalized(body[key],col);}catch(err){return validationError(res,key,err);}}if(!v.category||!v.name)return res.status(400).json({error:'category and name are required'});const r=await db.query(`INSERT INTO products (tenant_id,category,external_id,name,sku,price_per_day,price_type,width_ft,length_ft,capacity,photo_url,sort_order,visual_model_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[req.tenant.id,v.category,v.external_id,v.name,v.sku,v.price_per_day,v.price_type||'per_day',v.width_ft,v.length_ft,v.capacity,v.photo_url,v.sort_order==null?0:v.sort_order,v.visual_model_id]);res.status(201).json({product:r.rows[0]});});

router.patch('/:slug/products/:id', requireTenantRole('staff'), async (req,res)=>{const fields=req.body||{};const allowed=['category','name','sku','price_per_day','price_type','width_ft','length_ft','capacity','photo_url','external_id','sort_order','active','visual_model_id'];const map={pricePerDay:'price_per_day',priceType:'price_type',widthFt:'width_ft',lengthFt:'length_ft',photoUrl:'photo_url',externalId:'external_id',sortOrder:'sort_order',visualModelId:'visual_model_id'};const sets=[],values=[];let i=1;for(const [key,raw] of Object.entries(fields)){const col=map[key]||key;if(!allowed.includes(col))continue;let value;try{value=normalized(raw,col);}catch(err){return validationError(res,key,err);}sets.push(`${col}=$${i++}`);values.push(value);}if(!sets.length)return res.status(400).json({error:'No valid fields to update'});sets.push('updated_at=now()');values.push(req.params.id,req.tenant.id);const r=await db.query(`UPDATE products SET ${sets.join(',')} WHERE id=$${i} AND tenant_id=$${i+1} RETURNING *`,values);if(!r.rows[0])return res.status(404).json({error:'Product not found'});res.json({product:r.rows[0]});});

router.delete('/:slug/products/:id', requireTenantRole('staff'), async (req,res)=>{const r=await db.query('UPDATE products SET active=false,updated_at=now() WHERE id=$1 AND tenant_id=$2 RETURNING id',[req.params.id,req.tenant.id]);if(!r.rows[0])return res.status(404).json({error:'Product not found'});res.json({ok:true});});
module.exports=router;
