const crypto=require('crypto');
const express=require('express');
const db=require('../db');
const {requireTenantRole}=require('../middleware/requireAuth');
const {syncOrderEntitlement}=require('../orderProviders/friendlyOrderProvider');
const router=express.Router();
async function sendWebhook(tenant,eventType,data){if(!tenant.webhook_url)return;try{const payload={id:crypto.randomUUID(),type:eventType,createdAt:new Date().toISOString(),data};const body=JSON.stringify(payload);const signature=tenant.webhook_secret?crypto.createHmac('sha256',tenant.webhook_secret).update(body).digest('hex'):'';await fetch(tenant.webhook_url,{method:'POST',headers:{'Content-Type':'application/json','X-RentSketch-Signature':signature},body});}catch(err){console.error('[webhook] delivery failed for tenant',tenant.slug,err.message);}}
router.post('/:slug/quote-requests',async(req,res)=>{const tenant=(await db.query('SELECT * FROM tenants WHERE slug=$1',[req.params.slug])).rows[0];if(!tenant)return res.status(404).json({error:'Tenant not found'});const {designId,customerName,customerEmail,customerPhone,eventDate,guestCount,eventType,lineItems,estimateTotal,notes}=req.body||{};if(!customerName||!customerEmail)return res.status(400).json({error:'customerName and customerEmail are required'});if(designId){const d=(await db.query('SELECT tenant_id FROM designs WHERE id=$1',[designId])).rows[0];if(!d||d.tenant_id!==tenant.id)return res.status(400).json({error:'designId does not belong to this tenant'});}const r=await db.query(`INSERT INTO quote_requests (tenant_id,design_id,customer_name,customer_email,customer_phone,event_date,guest_count,event_type,line_items,estimate_total,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id,created_at`,[tenant.id,designId||null,customerName,customerEmail,customerPhone||null,eventDate||null,guestCount||null,eventType||null,JSON.stringify(lineItems||[]),estimateTotal||null,notes||null]);sendWebhook(tenant,'quote_request.created',{id:r.rows[0].id,createdAt:r.rows[0].created_at,customerName,customerEmail,eventDate,guestCount,estimateTotal});res.status(201).json({id:r.rows[0].id,createdAt:r.rows[0].created_at});});
router.get('/:slug/quote-requests',requireTenantRole('viewer'),async(req,res)=>{const r=await db.query(`SELECT qr.*,d.scene FROM quote_requests qr LEFT JOIN designs d ON d.id=qr.design_id WHERE qr.tenant_id=$1 ORDER BY qr.created_at DESC`,[req.tenant.id]);res.json({quoteRequests:r.rows});});
router.patch('/:slug/quote-requests/:id',requireTenantRole('staff'),async(req,res)=>{const {status,notes}=req.body||{};const r=await db.query(`UPDATE quote_requests SET status=COALESCE($1,status),notes=COALESCE($2,notes) WHERE id=$3 AND tenant_id=$4 RETURNING *`,[status||null,notes||null,req.params.id,req.tenant.id]);if(!r.rows[0])return res.status(404).json({error:'Quote request not found'});if(status)await syncOrderEntitlement(r.rows[0],req.tenant);res.json({quoteRequest:r.rows[0]});});
module.exports=router;
