const express=require('express');
const db=require('../db');
const {requireTenantRole}=require('../middleware/requireAuth');
const router=express.Router();
function publicShape(t){return{id:t.id,slug:t.slug,name:t.name,logoUrl:t.logo_url,contactEmail:t.contact_email,phone:t.phone,website:t.website,tagline:t.tagline,primaryColor:t.primary_color,secondaryColor:t.secondary_color,showPrices:t.show_prices,poweredByEnabled:t.powered_by_enabled};}
router.get('/generic',async(req,res)=>{const t=(await db.query('SELECT * FROM tenants WHERE slug=$1',['generic'])).rows[0];if(!t)return res.status(404).json({error:'Generic tenant not found'});res.json(publicShape(t));});
router.get('/:slug',async(req,res)=>{const t=(await db.query('SELECT * FROM tenants WHERE slug=$1',[req.params.slug])).rows[0];if(!t)return res.status(404).json({error:'Tenant not found'});res.json(publicShape(t));});
router.get('/:slug/admin',requireTenantRole('viewer'),async(req,res)=>{const t=req.tenant;res.json(Object.assign(publicShape(t),{embedKey:t.embed_key,allowedOrigins:t.allowed_origins,webhookUrl:t.webhook_url,hasWebhookSecret:Boolean(t.webhook_secret),subscriptionPlan:t.subscription_plan,subscriptionStatus:t.subscription_status,trialEndsAt:t.trial_ends_at,customerAccess:t.customer_access,passPriceCents:t.pass_price_cents,passDurationDays:t.pass_duration_days,activeOrderGraceDays:t.active_order_grace_days,creditPassToOrder:t.credit_pass_to_order,role:req.user.tenantRole}));});
router.patch('/:slug',requireTenantRole('admin'),async(req,res)=>{const body=req.body||{};const map={name:'name',logoUrl:'logo_url',contactEmail:'contact_email',phone:'phone',website:'website',tagline:'tagline',primaryColor:'primary_color',secondaryColor:'secondary_color',showPrices:'show_prices',poweredByEnabled:'powered_by_enabled',allowedOrigins:'allowed_origins',webhookUrl:'webhook_url',webhookSecret:'webhook_secret',customerAccess:'customer_access',passPriceCents:'pass_price_cents',passDurationDays:'pass_duration_days',activeOrderGraceDays:'active_order_grace_days',creditPassToOrder:'credit_pass_to_order'};const sets=[],values=[];let i=1;for(const [key,value] of Object.entries(body)){const col=map[key];if(!col)continue;sets.push(`${col}=$${i++}`);values.push(col==='allowed_origins'?JSON.stringify(value):value);}if(!sets.length)return res.status(400).json({error:'No valid fields to update'});sets.push('updated_at=now()');values.push(req.tenant.id);const r=await db.query(`UPDATE tenants SET ${sets.join(',')} WHERE id=$${i} RETURNING *`,values);res.json({tenant:publicShape(r.rows[0])});});
module.exports=router;
