const express=require('express');
const db=require('../db');
const {requireTenantRole}=require('../middleware/requireAuth');
const {validateWebhookUrl}=require('../outboundWebhook');
const router=express.Router();
function publicShape(t){return{id:t.id,slug:t.slug,name:t.name,logoUrl:t.logo_url,contactEmail:t.contact_email,phone:t.phone,website:t.website,tagline:t.tagline,primaryColor:t.primary_color,secondaryColor:t.secondary_color,showPrices:t.show_prices,poweredByEnabled:t.powered_by_enabled};}
function cleanOrigins(value){if(!Array.isArray(value))return{error:'allowedOrigins must be an array'};if(value.length>50)return{error:'Too many allowed origins'};const out=[];for(const raw of value){if(typeof raw!=='string'||raw.length>500)return{error:'Invalid allowed origin'};let u;try{u=new URL(raw);}catch(_){return{error:'Allowed origins must be valid http(s) origins'};}if(!['https:','http:'].includes(u.protocol)||u.username||u.password||u.pathname!=='/'||u.search||u.hash)return{error:'Allowed origins must contain only scheme, host, and optional port'};const origin=u.origin;if(!out.includes(origin))out.push(origin);}return{value:out};}
router.get('/generic',async(req,res)=>{const t=(await db.query('SELECT * FROM tenants WHERE slug=$1',['generic'])).rows[0];if(!t)return res.status(404).json({error:'Generic tenant not found'});res.json(publicShape(t));});
router.get('/:slug',async(req,res)=>{const t=(await db.query('SELECT * FROM tenants WHERE slug=$1',[req.params.slug])).rows[0];if(!t)return res.status(404).json({error:'Tenant not found'});res.json(publicShape(t));});
router.get('/:slug/admin',requireTenantRole('viewer'),async(req,res)=>{const t=req.tenant;res.json(Object.assign(publicShape(t),{embedKey:t.embed_key,allowedOrigins:t.allowed_origins,webhookUrl:t.webhook_url,hasWebhookSecret:Boolean(t.webhook_secret),subscriptionPlan:t.subscription_plan,subscriptionStatus:t.subscription_status,trialEndsAt:t.trial_ends_at,customerAccess:t.customer_access,passPriceCents:t.pass_price_cents,passDurationDays:t.pass_duration_days,activeOrderGraceDays:t.active_order_grace_days,creditPassToOrder:t.credit_pass_to_order,role:req.user.tenantRole}));});
router.patch('/:slug',requireTenantRole('admin'),async(req,res)=>{const body=req.body||{};const map={name:'name',logoUrl:'logo_url',contactEmail:'contact_email',phone:'phone',website:'website',tagline:'tagline',primaryColor:'primary_color',secondaryColor:'secondary_color',showPrices:'show_prices',poweredByEnabled:'powered_by_enabled',allowedOrigins:'allowed_origins',webhookUrl:'webhook_url',webhookSecret:'webhook_secret',customerAccess:'customer_access',passPriceCents:'pass_price_cents',passDurationDays:'pass_duration_days',activeOrderGraceDays:'active_order_grace_days',creditPassToOrder:'credit_pass_to_order'};const sets=[],values=[];let i=1;for(const [key,rawValue] of Object.entries(body)){const col=map[key];if(!col)continue;let value=rawValue;if(col==='webhook_url'){const checked=validateWebhookUrl(value);if(!checked.ok)return res.status(400).json({error:checked.error});value=checked.url;}else if(col==='webhook_secret'){if(value!=null&&typeof value!=='string')return res.status(400).json({error:'webhookSecret must be text'});if(typeof value==='string'&&value.length>512)return res.status(400).json({error:'webhookSecret is too long'});value=value||null;}else if(col==='allowed_origins'){const checked=cleanOrigins(value);if(checked.error)return res.status(400).json({error:checked.error});value=JSON.stringify(checked.value);}sets.push(`${col}=$${i++}`);values.push(value);}if(!sets.length)return res.status(400).json({error:'No valid fields to update'});sets.push('updated_at=now()');values.push(req.tenant.id);const r=await db.query(`UPDATE tenants SET ${sets.join(',')} WHERE id=$${i} RETURNING *`,values);res.json({tenant:publicShape(r.rows[0])});});
module.exports=router;
