const express = require('express');
const cors = require('cors');
const authRoutes=require('./routes/auth');
const tenantsRoutes=require('./routes/tenants');
const productsRoutes=require('./routes/products');
const designsRoutes=require('./routes/designs');
const designBackgroundsRoutes=require('./routes/designBackgrounds');
const quoteRequestsRoutes=require('./routes/quoteRequests');
const feedbackRoutes=require('./routes/feedback');
const visualLibraryRoutes=require('./routes/visualLibrary');
const paymentsRoutes=require('./routes/payments');
const stripeWebhookRoutes=require('./routes/stripeWebhook');
const consumerEventPassRoutes=require('./routes/consumerEventPass');
const businessSignupRoutes=require('./routes/businessSignup');
const businessBillingRoutes=require('./routes/businessBilling');
const connectRoutes=require('./routes/connect');
const adminRoutes=require('./routes/admin');
const embedRoutes=require('./routes/embed');
const webVitalsRoutes=require('./routes/webVitals');
const app=express();
const allowedOrigins=(process.env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim().replace(/\/$/, '')).filter(Boolean);
const production=process.env.NODE_ENV==='production';
if(production&&!allowedOrigins.length)console.error('[security] ALLOWED_ORIGINS is empty in production; cross-origin browser requests will be denied.');
function corsOrigin(origin,cb){if(!origin)return cb(null,true);const normalized=origin.replace(/\/$/,'');if(allowedOrigins.includes(normalized))return cb(null,true);if(!production&&!allowedOrigins.length)return cb(null,true);return cb(new Error('CORS origin denied'));}
app.disable('x-powered-by');
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Cross-Origin-Resource-Policy','cross-origin');next();});
app.use(cors({origin:corsOrigin,methods:['GET','HEAD','POST','PUT','PATCH','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization','X-Embed-Token','X-RentSketch-Signature','X-RentSketch-Session'],maxAge:86400}));
app.use('/api/stripe/webhook',express.raw({type:'application/json',limit:'256kb'}),stripeWebhookRoutes);
app.use(express.json({limit:'256kb'}));
app.get('/health',(req,res)=>res.json({ok:true}));
app.use('/api/auth',authRoutes);
app.use('/api/embed',embedRoutes);
app.use('/api/tenants',tenantsRoutes);
app.use('/api/tenants',productsRoutes);
app.use('/api/tenants',require('./routes/reviewPricing'));
app.use('/api/tenants',designBackgroundsRoutes);
app.use('/api/tenants',designsRoutes);
app.use('/api/tenants',quoteRequestsRoutes);
app.use('/api/tenants',feedbackRoutes);
app.use('/api/tenants',paymentsRoutes);
app.use('/api/tenants',connectRoutes);
app.use('/api/business',businessSignupRoutes);
app.use('/api/business',businessBillingRoutes);
app.use('/api/visual-library',visualLibraryRoutes);
app.use('/api/consumer',designBackgroundsRoutes);
app.use('/api/consumer',consumerEventPassRoutes);
app.use('/api/analytics/web-vitals',webVitalsRoutes);
app.use('/api/admin',adminRoutes);
app.use((err,req,res,next)=>{if(err&&err.message==='CORS origin denied')return res.status(403).json({error:'Origin not allowed'});console.error(err);if(err&&err.type==='entity.too.large')return res.status(413).json({error:'Request too large'});res.status(500).json({error:'Internal server error'});});
module.exports=app;
