const db = require('./db');
const BASE='https://www.friendlypartyrental.com', TARGET_EMAIL='customerservice@friendlypartyrental.com';
async function getText(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);try{const r=await fetch(url,{signal:c.signal,headers:{'user-agent':'RentSketchCatalogSync/1.0 (+https://rentsketch.com)'}});if(!r.ok)throw new Error(`${r.status} ${url}`);return await r.text();}finally{clearTimeout(t);}}
function decode(s){return String(s||'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');}
function strip(s){return decode(String(s||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim());}
function meta(h,k){const a=h.match(new RegExp('<meta[^>]+(?:property|name)=["\\\']'+k+'["\\\'][^>]+content=["\\\']([^"\\\']+)','i')),b=h.match(new RegExp('<meta[^>]+content=["\\\']([^"\\\']+)["\\\'][^>]+(?:property|name)=["\\\']'+k+'["\\\']','i'));return decode((a||b||[])[1]||'');}
function slug(url){try{return new URL(url).pathname.split('/').filter(Boolean).pop();}catch(_){return'';}}
function category(h){const b=strip((h.match(/Home\s*\/\s*([^<\/]+)\s*\//i)||[])[1]),s=b.toLowerCase();if(/tent/.test(s))return'tent';if(/table.*chair|chair/.test(s))return'chair';if(/table/.test(s))return'table';if(/linen/.test(s))return'linen';if(/light/.test(s))return'lighting';if(/dance|stage/.test(s))return'dance_floor';if(/bounce|water|inflatable/.test(s))return'inflatable';if(/photo/.test(s))return'photobooth';if(/concession/.test(s))return'concession';if(/generator/.test(s))return'generator';if(/game/.test(s))return'game';if(/package|wedding/.test(s))return'package';return b?b.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,''):'other';}
function parse(url,h){let ld=null;for(const m of h.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const o=JSON.parse(m[1]),l=Array.isArray(o)?o:(o['@graph']||[o]);ld=l.find(x=>x&&(x['@type']==='Product'||(Array.isArray(x['@type'])&&x['@type'].includes('Product'))));if(ld)break;}catch(_){}}const h1=strip((h.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)||[])[1]),name=(ld&&ld.name)||h1||meta(h,'og:title').replace(/\s*\|.*$/,'');let image=ld&&ld.image;if(Array.isArray(image))image=image[0];if(image&&typeof image==='object')image=image.url||image.contentUrl;image=image||meta(h,'og:image');let offer=ld&&ld.offers;if(Array.isArray(offer))offer=offer[0];let price=offer&&(offer.price||offer.lowPrice);if(price==null){const text=strip(h),pm=text.match(/Starting at\s*\$([\d,]+(?:\.\d{1,2})?)/i)||text.match(/\$([\d,]+(?:\.\d{1,2})?)\s*\/\s*day/i);price=pm&&pm[1];}price=price==null?null:Number(String(price).replace(/,/g,''));if(!name||!Number.isFinite(price))return null;const size=name.match(/(\d{1,3})\s*[x×]\s*(\d{1,3})/i),cap=strip(h).match(/(?:seats?|accommodates?|capacity)[^\d]{0,20}(\d{1,3})/i);return{externalId:'fpr:'+slug(url),name:strip(name),category:category(h),price,photoUrl:image||null,widthFt:size?Number(size[1]):null,lengthFt:size?Number(size[2]):null,capacity:cap?Number(cap[1]):null};}
async function discover(){const found=new Set(),maps=[BASE+'/sitemap.xml',BASE+'/sitemap_index.xml',BASE+'/sitemap-index.xml'];try{const r=await getText(BASE+'/robots.txt');for(const m of r.matchAll(/^Sitemap:\s*(\S+)/gim))maps.unshift(m[1]);}catch(_){}const seen=new Set();async function readMap(u,d){if(seen.has(u)||d>3)return;seen.add(u);try{const x=await getText(u),locs=Array.from(x.matchAll(/<loc>([^<]+)<\/loc>/gi),m=>decode(m[1].trim()));for(const loc of locs){if(/\/items\/[^/?#]+/i.test(loc))found.add(loc.split('?')[0]);else if(/sitemap/i.test(loc))await readMap(loc,d+1);}}catch(_){}}for(const m of maps)await readMap(m,0);if(!found.size){const seeds=[BASE+'/',BASE+'/items',BASE+'/category/tent-rentals',BASE+'/category/table-chair-rentals',BASE+'/category/bounce-house-rentals',BASE+'/category/linen-tablecloth-rentals',BASE+'/category/dance-floor-stage-rentals',BASE+'/category/photobooth-rentals',BASE+'/category/concession-machine-rentals',BASE+'/category/generator-rentals',BASE+'/category/yard-game-rentals',BASE+'/category/party-rental-packages'];for(const u of seeds){try{const h=await getText(u);for(const m of h.matchAll(/href=["']([^"']*\/items\/[^"'#?]+)["']/gi))found.add(new URL(decode(m[1]),BASE).href);}catch(_){}}}return Array.from(found);}
async function upsert(tenantId,p){const existing=await db.query('SELECT id FROM products WHERE tenant_id=$1 AND external_id=$2 LIMIT 1',[tenantId,p.externalId]);if(existing.rows[0]){await db.query(`UPDATE products SET category=$1,name=$2,price_per_day=$3,width_ft=$4,length_ft=$5,capacity=$6,photo_url=$7,active=true,updated_at=now() WHERE id=$8`,[p.category,p.name,p.price,p.widthFt,p.lengthFt,p.capacity,p.photoUrl,existing.rows[0].id]);return'updated';}await db.query(`INSERT INTO products (tenant_id,category,external_id,name,price_per_day,price_type,width_ft,length_ft,capacity,photo_url,sort_order,active) VALUES ($1,$2,$3,$4,$5,'per_day',$6,$7,$8,$9,0,true)`,[tenantId,p.category,p.externalId,p.name,p.price,p.widthFt,p.lengthFt,p.capacity,p.photoUrl]);return'inserted';}
async function syncFriendlyCatalog(){const tr=await db.query(`SELECT id,slug,name,contact_email FROM tenants WHERE lower(contact_email)=lower($1) OR lower(name) LIKE '%friendly party rental%' ORDER BY CASE WHEN lower(contact_email)=lower($1) THEN 0 ELSE 1 END LIMIT 1`,[TARGET_EMAIL]),tenant=tr.rows[0];if(!tenant){console.log('[catalog-sync] Friendly Party Rental tenant not found; skipped');return{skipped:true};}const urls=await discover();if(!urls.length)throw new Error('No Friendly Party Rental item URLs discovered');let imported=0,failed=0;for(let i=0;i<urls.length;i+=6)await Promise.all(urls.slice(i,i+6).map(async url=>{try{const p=parse(url,await getText(url));if(!p){failed++;return;}await upsert(tenant.id,p);imported++;}catch(e){failed++;console.warn('[catalog-sync] item failed',url,e.message);}}));console.log(`[catalog-sync] ${tenant.slug}: discovered=${urls.length} imported=${imported} failed=${failed}`);return{tenant:tenant.slug,discovered:urls.length,imported,failed};}
module.exports=syncFriendlyCatalog;
